window.JOBS_DATA = [
  {
    "basic_qualifications": "- 5+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with SQL<br/>- Experience in at least one modern scripting or programming language, such as Python, Java, Scala, or NodeJS<br/>- Experience mentoring team members on best practices<br/>- Bachelor's degree in computer science, engineering, analytics, mathematics, statistics, IT or equivalent",
    "business_category": "subsidiaries",
    "city": "Austin",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Help build the data foundation that keeps Amazon's fulfillment network running 24/7. Infrastructure Reliability is building an AI-powered platform that detects, diagnoses, and resolves incidents across thousands of sites globally, and none of it works without clean, reliable, well-modeled data.<br/><br/>You will own and evolve production data pipelines that power real-time incident detection and correlation, build the data lake and unified data models that unblock ML and autonomous resolution initiatives, and rescue historical telemetry data before it expires and becomes permanently unrecoverable. This is a high-ownership role with direct, visible impact on Amazon's global fulfillment operations, working closely with applied scientists who train models on the data you build.<br/><br/><br/>Key job responsibilities<br/>You will design, build, and operate ETL pipelines that ingest, transform, and correlate incident and telemetry data from sources including DynamoDB, OpenSearch, CloudWatch, and internal incident management systems, publishing curated datasets to our data lake and Andes for consumption by dashboards, applications, and ML models. You will take ownership of production pipelines, including scheduled batch processing jobs and Glue-based ETL workflows, ensuring reliability, monitoring, and timely resolution of pipeline issues.<br/><br/>You will build data retention and ingestion pipelines to preserve time-bound telemetry signals before source-system expiration windows, and you will design standardized ingestion frameworks that normalize data from many disparate sources into a common, science-consumable format. You will contribute to the design of a unified data lake architecture, including schema design, partitioning strategy, and access patterns, replacing fragmented, duplicated pipelines with a single source of truth.<br/><br/>You will partner closely with applied scientists and engineers to grasp data requirements for ML model training and feature engineering, and you will mentor other engineers on data engineering best practices, code quality, and pipeline design.<br/><br/>A day in the life<br/>You might start your day investigating a pipeline failure alert, tracing it back through Glue job logs to a schema change upstream. Later, you're in a design discussion with an applied scientist about what shape of data would best enable a new model, translating that into a concrete schema. In the afternoon, you're heads-down building a new ingestion adapter or reviewing a teammate's pull request. Your work directly determines what data is available, and reliable, for the platform's detection and reasoning capabilities.<br/><br/>Amazon offers a full range of benefits that support you and eligible family members, including domestic partners. Benefits can vary by location, the number of regularly scheduled hours you work, length of employment, and job status such as seasonal or temporary employment. The benefits that generally apply to regular, full-time employees include:<br/>1. Medical, Dental, and Vision Coverage<br/>2. Maternity and Parental Leave Options<br/>3. Paid Time Off (PTO)<br/>4. 401(k) Plan<br/><br/>If you are not sure that every qualification on the list above describes you exactly, we'd still love to hear from you! At Amazon, we value people with unique backgrounds, experiences, and skillsets. If you\u2019re passionate about this role and want to make an impact on a global scale, please apply!<br/><br/>About the team<br/>Infrastructure Reliability sits within Amazon's Robotics organization, building the platform that keeps fulfillment operations running no matter what breaks. We do not own any single domain; we build the data and orchestration layer that sees across all of them, identifying failures that cascade across team boundaries. We are a small, technically deep team building AI-powered detection and remediation capabilities at scale. We value ownership, rigor, and hands-on technical depth, and we move quickly from idea to production.",
    "department_cost_center": null,
    "description_short": "Help build the data foundation that keeps Amazon's fulfillment network running 24/7. Infrastructure Reliability is building an AI-powered platform that detects, diagnoses, and resolves incidents across",
    "display_distance": null,
    "id": "8cbd2975-0c74-49be-9443-45ea8dbcd6e5",
    "id_icims": "10489946",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10489946/senior-data-engineer-infrastructure-reliability",
    "job_schedule_type": "full-time",
    "location": "US, TX, Austin",
    "locations": [
      "{\"normalizedStateName\":\"Texas\",\"normalizedCountryCode\":\"USA\",\"city\":\"Austin\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, TX, Austin\",\"coordinates\":\"30.26759,-97.74299\",\"normalizedCountyName\":\"Travis\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Austin, Texas, USA\",\"location\":\"US, TX, Austin\",\"region\":\"TX\",\"buildingCodeList\":[\"AUS13\"],\"normalizedCityName\":\"Austin\"}"
    ],
    "normalized_location": "Austin, Texas, USA",
    "optional_search_labels": [],
    "posted_date": "August  3, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience operating large data warehouses<br/>- Master's degree in computer science, engineering, analytics, mathematics, statistics, IT or equivalent<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, TX, Austin - 154,600.00 - 209,100.00 USD annually",
    "primary_search_label": "subsidiaries.team-amazon-robotics",
    "source_system": "JobCreator",
    "state": "TX",
    "title": "Senior Data Engineer, Infrastructure Reliability",
    "university_job": null,
    "updated_time": "4 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10489946/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-amazon-robotics",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "R0835947-1",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "3 Locations",
    "posted_date": "2026-08-04T02:29:57.918601",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/MA---Wellesley/Senior-Data-Engineer_R0835947-1",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "basic_qualifications": "- 2+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with one or more query language (e.g., SQL, PL/SQL, DDL, MDX, HiveQL, SparkSQL, Scala)<br/>- Experience with database, data warehouse or data lake solutions<br/>- Experience with one or more scripting language (e.g., Python, KornShell)",
    "business_category": "operations",
    "city": "Bellevue",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Have you ever ordered a product from Amazon and been amazed at how fast it gets to you?<br/><br/>Every day Amazon engineers are relentlessly working to decrease the time between Click to Deliver for your products. The Amazon Fulfillment Technologies (AFT) team owns all of the software and infrastructure which powers Amazon's world-class fulfillment engine. Our team is building complex, massive data systems to capture data during every step in the automated pipeline and use that data to proactively predict efficiency and cost improvements to deliver the packages fast to our customers.<br/><br/>As an Amazon.com Big Data Engineer you will be working in one of the world's largest and most complex data warehouse environments. You should be skilled in the architecture of DW solutions for the Enterprise using multiple platforms (RDBMS, Columnar, Cloud). You should have experience in the design, creation, management, and business use of extremely large data-sets. You should have excellent business and communication skills to be able to work with business owners to develop and define key business questions, and to build data sets that answer those questions. Above all, you should be passionate about working with huge data sets and someone who loves to bring data-sets together to answer business questions and drive change.<br/><br/>As a Data Engineer in this role, you will develop new data engineering patterns that leverage a new cloud architecture, and will extend or migrate our existing data pipelines to this architecture as needed. You will also be assisting with integrating the Redshift platform as our primary processing platform to create the curated Amazon.com data model for the enterprise to leverage. You will be part of a team that builds the next generation data warehouse platform and to drive the adoption of new technologies and new practices in existing implementations. You will be responsible for designing and implementing the complex ETL pipelines in data warehouse platform and other BI solutions to support the rapidly growing and dynamic business demand for data, and use it to deliver the data as service which will have an immediate influence on day-to-day decision-making at Amazon.com.<br/><br/>Key job responsibilities<br/>- Build and maintain backend data infrastructure for analytical and visualization platforms, ensuring data is clean, fresh, and optimized for downstream consumption<br/><br/>- Translate business problem statements into technical data requirements, partnering with product management and stakeholders to define what data products to build<br/><br/>- Automate and optimize reporting processes to enable self-service analytics at scale, reducing manual effort and improving speed to insight<br/><br/>- Develop measurement frameworks and metrics that quantify deal execution performance and operational health<br/><br/>- Ensure data quality through monitoring, validation, auditing, and documentation of pipelines and data sources<br/><br/>- Leverage AWS services and generative AI to build next-generation data solutions that improve efficiency and unlock new analytical capabilities<br/><br/>A day in the life<br/>You will start your day checking pipeline health dashboards and addressing any overnight failures. You might spend the morning writing SQL to transform raw robotics data into productivity metrics, then pair with a senior engineer in the afternoon to design a new data model. You will participate in code reviews, contribute to on-call rotations, and work with business stakeholders to understand what questions they need data to answer.<br/><br/><br/><br/>About the team<br/>Amazon Fulfillment Technologies (AFT) powers Amazon\u2019s global fulfillment network. We invent and deliver software, hardware, and data science solutions that orchestrate processes, robots, machines, and people. We harmonize the physical and virtual world so Amazon customers can get what they want, when they want it.<br/><br/>The AFT Data Engineering team specifically owns the data pipelines and analytical tables that measure fulfillment center performance. Our data powers leadership decision-making from individual site managers to VP-level business reviews.",
    "department_cost_center": null,
    "description_short": "Have you ever ordered a product from Amazon and been amazed at how fast it gets to you?Every day Amazon engineers are relentlessly working to decrease the time between Click to Deliver for your products.",
    "display_distance": null,
    "id": "3bcbd6cb-c4c7-49ae-97c7-180737a188a1",
    "id_icims": "10490528",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Business Intelligence",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10490528/data-engineer-i-aft-bi-content",
    "job_schedule_type": "full-time",
    "location": "US, WA, Bellevue",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Bellevue\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Bellevue\",\"coordinates\":\"47.61001,-122.1872\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Bellevue, Washington, USA\",\"location\":\"US, WA, Bellevue\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA112\"],\"normalizedCityName\":\"Bellevue\"}"
    ],
    "normalized_location": "Bellevue, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "August  3, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Bellevue - 101,300.00 - 160,000.00 USD annually",
    "primary_search_label": "operations.team-amazon-fulfillment-technology",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer I, AFT BI Content",
    "university_job": null,
    "updated_time": "1 day",
    "url_next_step": "https://account.amazon.jobs/jobs/10490528/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-amazon-fulfillment-technology",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "210736986",
    "title": "Data Engineer III - Python / SQL",
    "company": "JPMorgan Chase",
    "location": "Plano, TX, United States",
    "posted_date": "2026-08-03T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210736986",
    "description_short": "Data Engineer III - Python / SQL",
    "source": "JPMorgan Chase"
  },
  {
    "id": "1970393556922931",
    "title": "Software Engineer: Data Platform/Analytics Intern Opportunities for University Students, Redmond",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-08-04T01:07:16",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556922931",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "210739969",
    "title": "Software Engineer II: Data Engineer",
    "company": "JPMorgan Chase",
    "location": "NY, United States",
    "posted_date": "2026-08-03T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210739969",
    "description_short": "Software Engineer II: Data Engineer",
    "source": "JPMorgan Chase"
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with one or more query language (e.g., SQL, PL/SQL, DDL, MDX, HiveQL, SparkSQL, Scala)<br/>- Experience with one or more scripting language (e.g., Python, KornShell)",
    "business_category": "advertising",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Amazon Advertising's Self-Service Support team ensures that advertisers using our applications can answer their own questions or solve their own problems whenever possible through Help content \u2014 and have an easy path to contact Amazon when it's not. We're looking for a curious and resourceful Data Engineer to own our infrastructure, deploy production models, fine-tune our data pipelines, and drive our agentic AI initiatives.<br/><br/>Key job responsibilities<br/>In this role, you'll be the engineering backbone of our team \u2014 owning the systems that power intelligent, self-service experiences for advertisers at scale. You'll deploy ML models into production, optimize data pipelines for performance and reliability, and lead the development of agentic workflows that autonomously reason and act on behalf of our customers.<br/><br/>## Key Responsibilities<br/><br/>-   **Infrastructure Ownership** \u2014 Design, build, and maintain scalable data infrastructure (data lakes, warehouses, streaming systems) that supports our analytics and ML workloads<br/>    <br/>-   **Production Model Deployment** \u2014 Own the end-to-end lifecycle of deploying ML models into production, including CI/CD pipelines, model serving, monitoring, and rollback strategies<br/>    <br/>-   **Pipeline Engineering & Optimization** \u2014 Develop and fine-tune ETL/ELT pipelines for performance, reliability, and cost efficiency; instrument for observability and SLA adherence<br/>    <br/>-   **Agentic AI Development** \u2014 Drive the design and implementation of agentic workflows \u2014 autonomous systems that reason, plan, and take actions to improve advertiser self-service experiences<br/>    <br/>-   **Reliability & Scalability** \u2014 Ensure production systems meet uptime, latency, and throughput targets; lead incident response and root-cause analysis<br/>    <br/>-   **Collaboration** \u2014 Partner with Data Scientists, Applied Scientists, Product, and Content teams to translate research into production-ready solutions that help advertisers help themselves",
    "department_cost_center": null,
    "description_short": "Amazon Advertising's Self-Service Support team ensures that advertisers using our applications can answer their own questions or solve their own problems whenever possible through Help content \u2014 and have",
    "display_distance": null,
    "id": "1297400c-b725-43f4-bb1c-cf0e53b39747",
    "id_icims": "10492138",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10492138/data-engineer-support-product-services",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA40\"],\"normalizedCityName\":\"Seattle\"}",
      "{\"normalizedStateName\":\"New York\",\"normalizedCountryCode\":\"USA\",\"city\":\"New York\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, NY, New York\",\"coordinates\":\"40.71453,-74.00712\",\"normalizedCountyName\":\"New York\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"New York, New York, USA\",\"location\":\"US, NY, New York\",\"region\":\"NY\",\"buildingCodeList\":[\"JFK19\"],\"normalizedCityName\":\"New York\"}",
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"SEATTLE\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, SEATTLE\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, SEATTLE\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA40\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "August  4, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience with any ETL tool like, Informatica, ODI, SSIS, BODI, Datastage, etc.<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, NY, New York - 111,400.00 - 185,000.00 USD annually<br/>USA, WA, SEATTLE - 101,300.00 - 160,000.00 USD annually",
    "primary_search_label": "advertising.team-amazon-ads",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, Support Product&Services",
    "university_job": null,
    "updated_time": "17 minutes",
    "url_next_step": "https://account.amazon.jobs/jobs/10492138/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-amazon-ads",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "1970393556866255",
    "title": "Solution Engineer - Cloud & AI Data Platform",
    "company": "Microsoft",
    "location": "United States, Multiple Locations, Multiple Locations",
    "posted_date": "2026-08-04T18:30:42",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556866255",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "210754163",
    "title": "Lead Software Engineer - Data Platform Engineer",
    "company": "JPMorgan Chase",
    "location": "Jersey City, NJ, United States",
    "posted_date": "2026-08-04T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210754163",
    "description_short": "Lead Software Engineer - Data Platform Engineer",
    "source": "JPMorgan Chase"
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with one or more query language (e.g., SQL, PL/SQL, DDL, MDX, HiveQL, SparkSQL, Scala)<br/>- Experience with one or more scripting language (e.g., Python, KornShell)",
    "business_category": "advertising",
    "city": "New York",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Amazon Advertising operates at the intersection of eCommerce and advertising, offering a rich array of digital display advertising solutions with the goal of helping our customers find and discover anything they want to buy. We help advertisers reach Amazon customers on Amazon.com, across our other owned and operated sites, on other high-quality sites across the web, and on millions of Kindles, tablets, and mobile devices. We start with the customer and work backwards in everything we do, including advertising. If you\u2019re interested in joining a rapidly growing team working to build a unique, world-class advertising group with a relentless focus on the customer, you\u2019ve come to the right place.<br/><br/>SDS is part of the Sales Intelligence, Technology, & Enablement organization (SITE). We are a big-data focused engineering team that provides unique, pan-Amazon datasets consolidating advertiser, seller, and vendor KPIs, exposed via data warehousing , fast APIs and agentic soutions. Our data platform is designed to serve Sales teams across WW Advertising orgs for various applications including business processes, ML, account management, marketing, and decisioning systems.<br/><br/><br/><br/>Key job responsibilities<br/>- Design, implement, and support data warehouse / data lake infrastructure using AWS big data stack, Python, Redshift.<br/>- Develop and manage ETLs to source data from various data lakes and create unified data model for analytics and reporting<br/>- Empower technical and non-technical, internal customers to drive their own analytics and reporting (self-serve reporting) and support ad-hoc reporting when needed.<br/>- Develop deep understanding of vast data sources and know exactly how, when, and which data to use to solve particular business problems.<br/>- Manage numerous requests concurrently and strategically, prioritizing when necessary collaborate across teams to deliver results.<br/>- Mentor other engineers, influence positively team culture, and help grow the team.",
    "department_cost_center": null,
    "description_short": "Amazon Advertising operates at the intersection of eCommerce and advertising, offering a rich array of digital display advertising solutions with the goal of helping our customers find and discover anything",
    "display_distance": null,
    "id": "4791939b-b272-466c-9737-59fcb1758d7a",
    "id_icims": "10492413",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10492413/data-engineer-i-sales-data-services-sds",
    "job_schedule_type": "full-time",
    "location": "US, NY, New York",
    "locations": [
      "{\"normalizedStateName\":\"New York\",\"normalizedCountryCode\":\"USA\",\"city\":\"New York\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, NY, New York\",\"coordinates\":\"40.71453,-74.00712\",\"normalizedCountyName\":\"New York\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"New York, New York, USA\",\"location\":\"US, NY, New York\",\"region\":\"NY\",\"buildingCodeList\":[\"JFK19\"],\"normalizedCityName\":\"New York\"}"
    ],
    "normalized_location": "New York, New York, USA",
    "optional_search_labels": [],
    "posted_date": "August  5, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience with any ETL tool like, Informatica, ODI, SSIS, BODI, Datastage, etc.<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, NY, New York - 111,400.00 - 185,000.00 USD annually",
    "primary_search_label": "advertising.team-amazon-ads",
    "source_system": "JobCreator",
    "state": "NY",
    "title": "Data Engineer I, Sales Data Services (SDS)",
    "university_job": null,
    "updated_time": "5 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10492413/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-amazon-ads",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "R0918733",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "5 Locations",
    "posted_date": "2026-08-05T01:42:58.908553",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/TX---Irving/Senior-Data-Engineer_R0918733",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using ETL/ELT processes experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using OLAP technologies experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using data modeling experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using SQL experience",
    "business_category": "aws",
    "city": "Seattle",
    "company_name": "Amazon Web Services, Inc.",
    "country_code": "USA",
    "description": "Amazon Web Services (AWS), World-Wide Public Sector Reporting and Analytics team is seeking a Data Engineer with broad technical skills to help build the infrastructure and tools required to support our Global Sales & Operations Organizations.<br/><br/>In this role, the ideal candidate will be responsible for developing and managing big data systems using advanced data engineering knowledge in the data warehousing space and redefining best practices with a cloud-based approach to scalability and automation. Additionally, you will be responsible for scaling our existing infrastructure, incorporating new data sources, and building robust data pipelines for production level systems. In partnership with machine learning engineers, business intelligence engineers and analysts, you will work backwards from our business questions to build reliable and scalable data solutions to meet the business needs. Finally, this individual will work closely with project management teams to ensure proper guidance, use cases, and documentation is available to our Sales and Operations teams.<br/><br/>Key job responsibilities<br/>Architect and implement scalable, reliable, and secure data pipelines and infrastructure to support analytics, reporting, and business operations.<br/>Design, develop, implement, test, document, and operate large-scale, high-volume, high-performance data structures for business intelligence analytics.<br/>Build robust and scalable data integration (ETL) pipelines using SQL, Python and AWS services such as Data Pipelines, Glue<br/>Implementing data structures using best practices in data modeling to provide on-line reporting and analysis using business intelligence tools and a logical abstraction layer against large, multi-dimensional datasets and multiple sources.<br/>Evaluating and making decisions around dataset implementations designed and proposed by peer data engineers. Mentor junior data engineers.<br/>Manage AWS resources including EC2, Redshift, S3, etc. Explore and learn the latest AWS technologies to provide new capabilities and increase efficiency.<br/>Participating in the full development life cycle, end-to-end, from design, implementation and testing, to documentation, delivery, support, and maintenance to produce comprehensive, usable dataset documentation and metadata.<br/><br/>About the team<br/>AWS values diverse experiences. Even if you do not meet all of the preferred qualifications and skills listed in the job description, we encourage candidates to apply. If your career is just starting, hasn\u2019t followed a traditional path, or includes alternative experiences, don\u2019t let it stop you from applying.<br/><br/>Why AWS? Amazon Web Services (AWS) is the world\u2019s most comprehensive and broadly adopted cloud platform. We pioneered cloud computing and never stopped innovating \u2014 that\u2019s why customers from the most successful startups to Global 500 companies trust our robust suite of products and services to power their businesses.<br/><br/>Inclusive Team Culture Here at AWS, it\u2019s in our nature to learn and be curious. Our employee-led affinity groups foster a culture of inclusion that empower us to be proud of our differences. Ongoing events and learning experiences, including our Conversations on Race and Ethnicity (CORE) and AmazeCon conferences, inspire us to never stop embracing our uniqueness.<br/><br/>Mentorship & Career Growth We\u2019re continuously raising our performance bar as we strive to become Earth\u2019s Best Employer. That\u2019s why you\u2019ll find endless knowledge-sharing, mentorship and other career-advancing resources here to help you develop into a better-rounded professional.<br/><br/>Work/Life Balance We value work-life harmony. Achieving success at work should never come at the expense of sacrifices at home, which is why we strive for flexibility as part of our working culture. When we feel supported in the workplace and at home, there\u2019s nothing we can\u2019t achieve in the cloud.<br/><br/>AWS Sales, Marketing, and Global Services (SMGS) is responsible for driving revenue, adoption, and growth from the largest and fastest growing small- and mid-market accounts to enterprise-level customers including public sector. The AWS Global Support team interacts with leading companies and believes that world-class support is critical to customer success. AWS Support also partners with a global list of customers that are building mission-critical applications on top of AWS services.",
    "department_cost_center": null,
    "description_short": "Amazon Web Services (AWS), World-Wide Public Sector Reporting and Analytics team is seeking a Data Engineer with broad technical skills to help build the infrastructure and tools required to support our",
    "display_distance": null,
    "id": "433f734f-627a-4369-8b51-3d8bc9fd4a8e",
    "id_icims": "10493224",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10493224/data-engineer-ii-data-management-team",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA44\"],\"normalizedCityName\":\"Seattle\"}",
      "{\"normalizedStateName\":\"Virginia\",\"normalizedCountryCode\":\"USA\",\"city\":\"Herndon\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, VA, Herndon\",\"coordinates\":\"38.96973,-77.385\",\"normalizedCountyName\":\"Fairfax\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Herndon, Virginia, USA\",\"location\":\"US, VA, Herndon\",\"region\":\"VA\",\"buildingCodeList\":[\"IAD28\"],\"normalizedCityName\":\"Herndon\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "August  5, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, VA, Herndon - 132,100.00 - 178,800.00 USD annually<br/>USA, WA, Seattle - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "aws.team-sales-primary",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer II, Data Management Team",
    "university_job": null,
    "updated_time": "5 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10493224/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-sales-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "1970393556957551",
    "title": "Senior Solution Engineer - Cloud & AI Data Platform",
    "company": "Microsoft",
    "location": "United States, Multiple Locations, Multiple Locations",
    "posted_date": "2026-08-05T18:55:40",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556957551",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "1970393556943784",
    "title": "Data Pipeline Engineer",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-08-05T18:27:30",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556943784",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "R0990429",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "IL - Work from home",
    "posted_date": "2026-08-05T07:40:18.857999",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/IL---Work-from-home/Senior-Data-Engineer_R0990429",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "R0990454-1",
    "title": "Data Engineer",
    "company": "CVS Health",
    "location": "16 Locations",
    "posted_date": "2026-08-05T07:40:18.858003",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/IL---Work-from-home/Data-Engineer_R0990454-1",
    "description_short": "Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "210777100",
    "title": "Compute Infrastructure Platforms Lead Data Engineer",
    "company": "JPMorgan Chase",
    "location": "LONDON, United Kingdom",
    "posted_date": "2026-08-05T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210777100",
    "description_short": "Compute Infrastructure Platforms Lead Data Engineer",
    "source": "JPMorgan Chase"
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- Experience with SQL<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "finance",
    "city": "New York",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "We are seeking a recent college graduate (undergrad) who has traversed their academic career learning and experimenting with AI. We want you to bring this new way of thinking to Amazon Ads!  You will use these skills to further the development and application of analytics methods to examine the complex data flows of Amazon Ads and to translate deep-dives into actionable insights for our product teams. In this role you will develop new tools to analyze our advertising data to help improve the performance of our bidding algorithms, targeting and relevance systems, help advance our supply strategy, and evaluate the adoption and impact of feature releases.<br/><br/>Key job responsibilities<br/>Analyze data trends regarding supply, optimization, ad load, and advertising mix effects that affect advertiser performance and contribute to achieving advertiser goals<br/>Present papers to senior leaders on issues like feature development impact on identity recognition rates, and changes of ad selection systems to improve fill rate highlighting insights that will inform our business development and engineering roadmaps<br/>Formalize our analytics approach to Ads auctions by analyzing bid spreads, auction depth, and simulating impacts of potential auction structure changes<br/>Identify, standardize, and operationalize KPIs to effectively measure the performance of all systems involved in ad serving, and use trend insights to inform business priorities<br/>Partner with engineering teams to define data logging requirements and getting these prioritized in engineering roadmaps<br/>Validate financial models through analysis<br/>Develop and own ad revenue and supply intelligence analytics decks that provide ongoing deep-dives<br/><br/>A day in the life<br/>The Ads Scientist will work closely with business leaders and engineers on developing common data architecture that will optimize our data logging at different grains, and will allow data interoperability from bid flow to optimization to campaign delivery. The candidate will then analyze the data and present papers and ongoing reports on actionable insights.<br/><br/>About the team<br/>The Ads Science Product Team's Mission: Work alongside those who need product data to apply objective perspective and business logic to uncover insights, advise strategic decisions, and adjust to industry changes.",
    "department_cost_center": null,
    "description_short": "We are seeking a recent college graduate (undergrad) who has traversed their academic career learning and experimenting with AI. We want you to bring this new way of thinking to Amazon Ads!  You will use",
    "display_distance": null,
    "id": "72dd84eb-cb21-42b1-9ac5-77fc8aeadd6b",
    "id_icims": "10494000",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10494000/data-engineer-data-science-focus-ads-science-analysis-tech-asat",
    "job_schedule_type": "full-time",
    "location": "US, NY, New York",
    "locations": [
      "{\"normalizedStateName\":\"New York\",\"normalizedCountryCode\":\"USA\",\"city\":\"New York\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, NY, New York\",\"coordinates\":\"40.71453,-74.00712\",\"normalizedCountyName\":\"New York\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"New York, New York, USA\",\"location\":\"US, NY, New York\",\"region\":\"NY\",\"buildingCodeList\":[\"JFK24\"],\"normalizedCityName\":\"New York\"}"
    ],
    "normalized_location": "New York, New York, USA",
    "optional_search_labels": [],
    "posted_date": "August  6, 2026",
    "preferred_qualifications": "- Experience using AI to automate and build with github (other sources) to showcase projects.<br/>- Proficiency in at least one programming language \u2014 Python, R, or SQL<br/>- Foundational knowledge of statistical methods (hypothesis testing, regression, probability)<br/>- Ability to query, clean, and transform data (SQL required)<br/>- Basic understanding of ML concepts (classification, clustering, regression models)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, NY, New York - 111,400.00 - 185,000.00 USD annually",
    "primary_search_label": "finance.team-gmac",
    "source_system": "JobCreator",
    "state": "NY",
    "title": "Data Engineer- Data Science Focus, Ads Science Analysis & Tech (ASAT)",
    "university_job": null,
    "updated_time": "about 1 hour",
    "url_next_step": "https://account.amazon.jobs/jobs/10494000/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-gmac",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- Bachelor's degree<br/>- 3+ years of data warehouse technical architectures, data modeling, infrastructure components, ETL/ ELT and reporting/analytic tools and environments, data structures and hands-on SQL coding experience<br/>- Experience with database, data warehouse or data lake solutions",
    "business_category": "entertainment",
    "city": "Culver City",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Amazon's Creator Services leads creator programs that span media, commerce, and culture. The Creator Services team includes Creator Partnerships, creator content studio Wondery, and physical production facilities Studio126. We connect creators and Amazon's diverse businesses, helping bring big ideas to life across Wondery, Amazon Music, Twitch, Audible, Amazon Games, and beyond. Join us in making Amazon the home for creators. <br/><br/>We are seeking a skilled Data Engineer to join our Data & Tech team in building robust, production-ready systems that drive creator monetization at scale. Operating at the intersection of data and software engineering, you will collaborate with Business Intelligence engineers and cross-functional business stakeholders to standardize and curate datasets that underpin AI-driven initiatives and self-service analytics capabilities. You will also design and build internal tools and software that automate workflows, improve data accessibility, and accelerate creator monetization outcomes. This role sits within the Creator Services data and tech team, and also supports the Creator Ad Partnerships team. <br/><br/>Key job responsibilities<br/>- Design, build, and maintain production-grade ETL/ELT pipelines that process data at scale with high reliability and performance <br/><br/>- Architect and curate data models, warehouses, and dimensional schemas that serve as the foundation for self-service analytics and AI initiatives <br/><br/>- Drive end-to-end technical ownership of data platform components \u2014 from system design and architecture reviews to deployment, monitoring, and incident response <br/><br/>- Leverage AWS services \u2014 including Redshift, S3, Glue, Lambda, ECS, DynamoDB, and Bedrock \u2014 to build scalable and cost-efficient data platforms <br/><br/>- Partner with BI engineers, program managers, and business stakeholders to translate data needs into technical solutions, while advocating for data engineering best practices across the team ",
    "department_cost_center": null,
    "description_short": "Amazon's Creator Services leads creator programs that span media, commerce, and culture. The Creator Services team includes Creator Partnerships, creator content studio Wondery, and physical production",
    "display_distance": null,
    "id": "d5c90738-a0d4-4992-9e78-16eeb0888434",
    "id_icims": "10495351",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Project/Program/Product Management--Non-Tech",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10495351/data-engineer-ii-creator-services",
    "job_schedule_type": "full-time",
    "location": "US, CA, Culver City",
    "locations": [
      "{\"normalizedStateName\":\"California\",\"normalizedCountryCode\":\"USA\",\"city\":\"Culver City\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, CA, Culver City\",\"coordinates\":\"34.02202,-118.39589\",\"normalizedCountyName\":\"Los Angeles\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Culver City, California, USA\",\"location\":\"US, CA, Culver City\",\"region\":\"CA\",\"buildingCodeList\":[\"LAX35\"],\"normalizedCityName\":\"Culver City\"}"
    ],
    "normalized_location": "Culver City, California, USA",
    "optional_search_labels": [],
    "posted_date": "August  6, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/>- Strong foundation in data governance, access controls, and compliance standards (e.g., IAM least-privilege, data classification, security certifications)<br/>- Demonstrated ability to provide technical leadership and advocating for data engineering best practices across cross-functional teams<br/>- Skilled at designing and building internal tools, APIs, or software applications that serve data products or automate business processes<br/>- Experience applying AI/ML technologies (e.g., large language models, generative AI, or predictive modeling) to data engineering or automation use cases<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Los Angeles County applicants: Job duties for this position include: work safely and cooperatively with other employees, supervisors, and staff; adhere to standards of excellence despite stressful conditions; communicate effectively and respectfully with employees, supervisors, and staff to ensure exceptional customer service; and follow all federal, state, and local laws and Company policies. Criminal history may have a direct, adverse, and negative relationship with some of the material job duties of this position. These include the duties and responsibilities listed above, as well as the abilities to adhere to company policies, exercise sound judgment, effectively manage stress and work safely and respectfully with others, exhibit trustworthiness and professionalism, and safeguard business operations and the Company\u2019s reputation. Pursuant to the Los Angeles County Fair Chance Ordinance, we will consider for employment qualified applicants with arrest and conviction records.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, CA, Culver City - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "entertainment.no-team-listed",
    "source_system": "JobCreator",
    "state": "CA",
    "title": "Data Engineer II, Creator Services",
    "university_job": null,
    "updated_time": "3 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10495351/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "no-team-listed",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "1970393556933657",
    "title": "Senior Data Engineer",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-08-06T22:34:49",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556933657",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "R0999180-1",
    "title": "Data Engineer with GCP experience",
    "company": "CVS Health",
    "location": "FL - Work from home",
    "posted_date": "2026-08-08T01:45:53.453185",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/FL---Work-from-home/Data-Engineer-with-GCP-experience_R0999180-1",
    "description_short": "Data Engineer with GCP experience",
    "source": "CVS Health"
  },
  {
    "id": "R0999424",
    "title": "Data Engineer",
    "company": "CVS Health",
    "location": "IL - Buffalo Grove",
    "posted_date": "2026-08-07T13:01:57.270110",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/IL---Buffalo-Grove/Data-Engineer_R0999424",
    "description_short": "Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "210759999",
    "title": "Data Engineer",
    "company": "JPMorgan Chase",
    "location": "Hyderabad, Telangana, India",
    "posted_date": "2026-08-07T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210759999",
    "description_short": "Data Engineer",
    "source": "JPMorgan Chase"
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "aws",
    "city": "Austin",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Sales, Marketing and Global Services (SMGS)<br/>AWS Sales, Marketing, and Global Services (SMGS) is responsible for driving revenue, adoption, and growth from the largest and fastest growing small- and mid-market accounts to enterprise-level customers including public sector. The AWS Global Support team interacts with leading companies and believes that world-class support is critical to customer success. AWS Support also partners with a global list of customers that are building mission-critical applications on top of AWS services.<br/><br/><br/>The AWS Marketplace team is looking for a Data Engineer to play a key role in building insights from our large and ever-growing sets of partner and customer data. Are you passionate about highly scalable data platforms and visualization? Do you enjoy building end to end analytics solutions to help drive business decisions? If so, this role will challenge and excite you!<br/><br/>The Data Engineer will design, develop, implement, test, document, and operate large-scale, high-volume, high-performance data structures for analytics. Implement data ingestion routines both real time and batch using best practices in data modeling, ETL/ELT processes leveraging AWS technologies and data tools. Provide on-line reporting and analysis using business intelligence tools and a logical abstraction layer against large, multi-dimensional datasets and multiple sources. Produce comprehensive, usable dataset documentation and metadata. Provides input and recommendations on technical issues.<br/><br/>10010",
    "department_cost_center": null,
    "description_short": "Sales, Marketing and Global Services (SMGS)AWS Sales, Marketing, and Global Services (SMGS) is responsible for driving revenue, adoption, and growth from the largest and fastest growing small- and mid-market",
    "display_distance": null,
    "id": "400738d8-70fe-41fe-9849-f9d85b8b0fc2",
    "id_icims": "10496061",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10496061/data-engineer-marketplace",
    "job_schedule_type": "full-time",
    "location": "US, TX, Austin",
    "locations": [
      "{\"normalizedStateName\":\"Texas\",\"normalizedCountryCode\":\"USA\",\"city\":\"Austin\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, TX, Austin\",\"coordinates\":\"30.26759,-97.74299\",\"normalizedCountyName\":\"Travis\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Austin, Texas, USA\",\"location\":\"US, TX, Austin\",\"region\":\"TX\",\"buildingCodeList\":[\"AUS16\"],\"normalizedCityName\":\"Austin\"}"
    ],
    "normalized_location": "Austin, Texas, USA",
    "optional_search_labels": [
      "aws.team-aspo"
    ],
    "posted_date": "August  7, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, TX, Austin - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "aws.team-data-science-primary",
    "source_system": "JobCreator",
    "state": "TX",
    "title": "Data Engineer, Marketplace",
    "university_job": null,
    "updated_time": "2 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10496061/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-data-science-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "aws",
    "city": "Bellevue",
    "company_name": "Amazon Data Services, Inc.",
    "country_code": "USA",
    "description": "AWS Infrastructure Services owns the design, planning, delivery, and operation of all AWS global infrastructure. In other words, we\u2019re the people who keep the cloud running. We support all AWS data centers and all of the servers, storage, networking, power, and cooling equipment that ensure our customers have continual access to the innovation they rely on. We work on the most challenging problems, with thousands of variables impacting the supply chain \u2014 and we\u2019re looking for talented people who want to help. <br/> <br/>You\u2019ll join a diverse team of software, hardware, and network engineers, supply chain specialists, security experts, operations managers, and other vital roles. You\u2019ll collaborate with people across AWS to help us deliver the highest standards for safety and security while providing seemingly infinite capacity at the lowest possible cost for our customers. And you\u2019ll experience an inclusive culture that welcomes bold ideas and empowers you to own them to completion.<br/><br/>We are looking for a talented Data Engineer to join the Manufacturing Operations, Transportation Operations, and Reverse (MOTOR) organization in support of our Supply Chain Intelligence team. MOTOR manages the manufacturing of datacenter racks and the movement of racks/parts through the supply chain, consisting of transportation, warehousing, and reverse logistics into and out of the data centers. This role performs helps connect the different systems across the supply chain together so operational teams have clean, actionable data to work with. This requires someone with strong analytic skills and business acumen who can work with stakeholders on strategic projects across MOTOR.  <br/><br/>The ideal candidate relishes working with large volumes of data, enjoys the challenge of highly complex technical contexts, and, above all else, is passionate about data and analytics. Must be an expert working with data modeling with un/structured data, ingestion pipelines and ETL design and business intelligence tools with the business to identify strategic opportunities where improvements in data infrastructure creates out-sized business impact. Candidate is a self-starter, comfortable with ambiguity, able to think big (while paying careful attention to detail), mentors other engineers in team on high quality tech, and enjoys working in a fast-paced team. Candidate will have a chance to architect the data pipelines needed for optimization and predictive analysis. We're excited to talk to those up to the challenge!<br/><br/><br/><br/>Key job responsibilities<br/>- Build and maintain the infrastructure to answer questions with data, using software engineering best practices, data management fundamentals, data storage principles, recent advances in distributed systems, and operational excellence best practices. Build datasets that analysts and scientists use to generate actionable insights.<br/>- Define the data engineering processes that leverage various AWS services to improve accessibility, redundancy, data integrity, cost, and storage requirements.<br/>- Develop high quality solutions for the faster development of the products/models that solve the business needs in a scalable format, while also anticipating future requirements.<br/>- Collaborate with Research/Applied Scientists, Data Engineers, Business Intelligence Engineers, Data Scientists, Business Analysts, and Product/Program Managers to understand the business and technical requirements, and make decisions that help make the products/programs smoother.<br/> - Interface with other technology/data engineering teams to extract, transform, and load data from a wide variety of data sources using and AWS data technologies.<br/>- Lead the technical design and implementation of the data infrastructure.<br/>- Design and manage data audit, quality, and reconciliation processes in collaboration with various stakeholders.<br/><br/><br/><br/>About the team<br/>This team provides data engineering and business intelligence engineering services to the rest of MOTOR. We are the data experts behind the scenes helping the operational teams focus on operations by ensuring they have accurate, timely data and provide business insights to help improve operational excellence.<br/><br/>*Why AWS*<br/>Amazon Web Services (AWS) is the world\u2019s most comprehensive and broadly adopted cloud platform. We pioneered cloud computing and never stopped innovating \u2014 that\u2019s why customers from the most successful startups to Global 500 companies trust our robust suite of products and services to power their businesses.<br/><br/>*Diverse Experiences*<br/>Amazon values diverse experiences. Even if you do not meet all of the preferred qualifications and skills listed in the job description, we encourage candidates to apply. If your career is just starting, hasn\u2019t followed a traditional path, or includes alternative experiences, don\u2019t let it stop you from applying.<br/><br/>*Work/Life Balance*<br/>We value work-life harmony. Achieving success at work should never come at the expense of sacrifices at home, which is why we strive for flexibility as part of our working culture. When we feel supported in the workplace and at home, there\u2019s nothing we can\u2019t achieve in the cloud.<br/><br/>*Inclusive Team Culture*<br/>Here at AWS, it\u2019s in our nature to learn and be curious. Our employee-led affinity groups foster a culture of inclusion that empower us to be proud of our differences. Ongoing events and learning experiences, including our Conversations on Race and Ethnicity (CORE) and AmazeCon (gender diversity) conferences, inspire us to never stop embracing our uniqueness.<br/><br/>*Mentorship and Career Growth*<br/>We\u2019re continuously raising our performance bar as we strive to become Earth\u2019s Best Employer. That\u2019s why you\u2019ll find endless knowledge-sharing, mentorship and other career-advancing resources here to help you develop into a better-rounded professional.",
    "department_cost_center": null,
    "description_short": "AWS Infrastructure Services owns the design, planning, delivery, and operation of all AWS global infrastructure. In other words, we\u2019re the people who keep the cloud running. We support all AWS data centers",
    "display_distance": null,
    "id": "abc13f6c-074d-4b9e-9cca-633e91441f02",
    "id_icims": "10495750",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Business Intelligence",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10495750/data-engineer-aws-infrastructure-supply-chain-intelligence",
    "job_schedule_type": "full-time",
    "location": "US, WA, Bellevue",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Bellevue\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Bellevue\",\"coordinates\":\"47.61001,-122.1872\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Bellevue, Washington, USA\",\"location\":\"US, WA, Bellevue\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA112\"],\"normalizedCityName\":\"Bellevue\"}",
      "{\"normalizedStateName\":\"Virginia\",\"normalizedCountryCode\":\"USA\",\"city\":\"Arlington\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, VA, Arlington\",\"coordinates\":\"38.8905,-77.08629\",\"normalizedCountyName\":\"Arlington\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Arlington, Virginia, USA\",\"location\":\"US, VA, Arlington\",\"region\":\"VA\",\"buildingCodeList\":[\"WAS17\"],\"normalizedCityName\":\"Arlington\"}"
    ],
    "normalized_location": "Bellevue, Washington, USA",
    "optional_search_labels": [
      "aws.team-ais",
      "aws.team-supply-chain"
    ],
    "posted_date": "August  7, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, VA, Arlington - 132,100.00 - 178,800.00 USD annually<br/>USA, WA, Bellevue - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "aws.team-support",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer , AWS Infrastructure Supply Chain Intelligence",
    "university_job": null,
    "updated_time": "3 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10495750/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-support",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with one or more query language (e.g., SQL, PL/SQL, DDL, MDX, HiveQL, SparkSQL, Scala)<br/>- Experience with one or more scripting language (e.g., Python, KornShell)",
    "business_category": "advertising",
    "city": "New York",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Amazon Advertising operates at the intersection of eCommerce and advertising, offering a rich array of digital display advertising solutions with the goal of helping our customers find and discover anything they want to buy. We help advertisers reach Amazon customers on Amazon.com, across our other owned and operated sites, on other high-quality sites across the web, and on millions of Kindles, tablets, and mobile devices. We start with the customer and work backwards in everything we do, including advertising. If you\u2019re interested in joining a rapidly growing team working to build a unique, world-class advertising group with a relentless focus on the customer, you\u2019ve come to the right place.<br/><br/>SDS is part of the Sales Intelligence, Technology, & Enablement organization (SITE). We are a big-data focused engineering team that provides unique, pan-Amazon datasets consolidating advertiser, seller, and vendor KPIs, exposed via data warehousing , fast APIs and agentic soutions. Our data platform is designed to serve Sales teams across WW Advertising orgs for various applications including business processes, ML, account management, marketing, and decisioning systems.<br/><br/><br/><br/>Key job responsibilities<br/>Key job responsibilities<br/>\u2022\tDesign, implement, and support data warehouse / data lake infrastructure using AWS big data stack, Python, Redshift.<br/>\u2022\tDevelop and manage ETLs to source data from various data lakes and create unified data model for analytics and reporting<br/>\u2022\tEmpower technical and non-technical, internal customers to drive their own analytics and reporting (self-serve reporting) and support ad-hoc reporting when needed.<br/>\u2022\tDevelop deep understanding of vast data sources and know exactly how, when, and which data to use to solve particular business problems.<br/>\u2022\tManage numerous requests concurrently and strategically, prioritizing when necessary collaborate across teams to deliver results.<br/>\u2022\tMentor other engineers, influence positively team culture, and help grow the team.",
    "department_cost_center": null,
    "description_short": "Amazon Advertising operates at the intersection of eCommerce and advertising, offering a rich array of digital display advertising solutions with the goal of helping our customers find and discover anything",
    "display_distance": null,
    "id": "0dc75c47-0576-454e-9329-d2b512f27443",
    "id_icims": "10496112",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10496112/data-engineer-i-sales-data-services-sds",
    "job_schedule_type": "full-time",
    "location": "US, NY, New York",
    "locations": [
      "{\"normalizedStateName\":\"New York\",\"normalizedCountryCode\":\"USA\",\"city\":\"New York\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, NY, New York\",\"coordinates\":\"40.71453,-74.00712\",\"normalizedCountyName\":\"New York\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"New York, New York, USA\",\"location\":\"US, NY, New York\",\"region\":\"NY\",\"buildingCodeList\":[\"JFK19\"],\"normalizedCityName\":\"New York\"}"
    ],
    "normalized_location": "New York, New York, USA",
    "optional_search_labels": [],
    "posted_date": "August  7, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience with any ETL tool like, Informatica, ODI, SSIS, BODI, Datastage, etc.<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, NY, New York - 111,400.00 - 185,000.00 USD annually",
    "primary_search_label": "advertising.team-amazon-ads",
    "source_system": "JobCreator",
    "state": "NY",
    "title": "Data Engineer I, Sales Data Services (SDS)",
    "university_job": null,
    "updated_time": "3 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10496112/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-amazon-ads",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 3+ years of non-internship professional software development experience<br/>- 2+ years of non-internship design or architecture (design patterns, reliability and scaling) of new and existing systems experience<br/>- Experience programming with at least one software programming language",
    "business_category": "aws",
    "city": "East Palo Alto",
    "company_name": "Amazon Development Center U.S., Inc.",
    "country_code": "USA",
    "description": "Want to change the world with Big Data and Analytics? Come join us on the Amazon Web services (AWS) Elastic MapReduce (EMR) team!<br/>EMR is a massively scaled distributed service that gives users fast and predictable Big Data performance with clusters running Hadoop, Hive, Pig, Impala, Spark, Presto, HBase and more, with the ability to effortlessly scale up and down as needed. We run millions of customer clusters, enabling processing on vast datasets.<br/><br/>We are developing innovative new features including the next-generation cluster management system, real-time processing for big data and intuitive ways of interacting with data, and we\u2019re looking for top engineers to build them from the ground up.<br/>This is a hands-on position where you will be do everything from designing and building extremely stable components and features for the savviest customers in the business to help them get the best results.<br/><br/>You will have a chance to work with the open source community and contribute significant portions its software to open source projects possibly including Hadoop, Spark, Pig and Hbase. You need to not only be a top software developer with excellent programming skills, an understanding of big data and parallelization, and a stellar record of delivery but also excel at leadership and customer obsession and have a real passion for massive-scale computing. If you want to truly test your mettle against the hardest challenges in distributed systems to build solutions for large scale problems in a wide variety of domains, come join our group.<br/><br/>Utility Computing (UC)<br/>AWS Utility Computing (UC) provides product innovations \u2014 from foundational services such as Amazon\u2019s Simple Storage Service (S3) and Amazon Elastic Compute Cloud (EC2), to consistently released new product innovations that continue to set AWS\u2019s services and features apart in the industry. As a member of the UC organization, you\u2019ll support the development and management of Compute, Database, Storage, Internet of Things (Iot), Platform, and Productivity Apps services in AWS, including support for customers who require specialized security solutions for customers who require specialized security solutions for their cloud services.<br/><br/>Key job responsibilities<br/>- Translation of complex functional and technical requirements into detailed architecture and design<br/>- Deliver systems and features with top-notch quality, on time<br/>- Develop new technologies for monitoring production clusters<br/>- Own the software development process end-to-end, including: working with engineers and product managers to develop requirements; designing, architecting, planning, implementing, and testing new systems and features; deploying, and operating the production EMR systems.<br/><br/>About the team<br/>About AWS <br/>AWS values diverse experiences. Even if you do not meet all of the preferred qualifications and skills listed in the job description, we encourage candidates to apply. If your career is just starting, hasn\u2019t followed a traditional path, or includes alternative experiences, don\u2019t let it stop you from applying. <br/><br/>Why AWS? Amazon Web Services (AWS) is the world\u2019s most comprehensive and broadly adopted cloud platform. We pioneered cloud computing and never stopped innovating \u2014 that\u2019s why customers from the most successful startups to Global 500 companies trust our robust suite of products and services to power their businesses. <br/><br/>Inclusive Team Culture Here at AWS, it\u2019s in our nature to learn and be curious. Our employee-led affinity groups foster a culture of inclusion that empower us to be proud of our differences. Ongoing events and learning experiences, including our Conversations on Race and Ethnicity (CORE) and AmazeCon  conferences, inspire us to never stop embracing our uniqueness. <br/><br/>Mentorship & Career Growth We\u2019re continuously raising our performance bar as we strive to become Earth\u2019s Best Employer. That\u2019s why you\u2019ll find endless knowledge-sharing, mentorship and other career-advancing resources here to help you develop into a better-rounded professional. <br/><br/>Work/Life Balance We value work-life harmony. Achieving success at work should never come at the expense of sacrifices at home, which is why we strive for flexibility as part of our working culture. When we feel supported in the workplace and at home, there\u2019s nothing we can\u2019t achieve in the cloud.",
    "department_cost_center": null,
    "description_short": "Want to change the world with Big Data and Analytics? Come join us on the Amazon Web services (AWS) Elastic MapReduce (EMR) team!EMR is a massively scaled distributed service that gives users fast and",
    "display_distance": null,
    "id": "0ed0a8bf-9cb7-4c24-827b-dac7479dcd7f",
    "id_icims": "10496096",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Software Development",
    "job_function_id": null,
    "job_path": "/en/jobs/10496096/software-development-engineer-big-data-aws-elastic-mapreduce-emr-emr-eks",
    "job_schedule_type": "full-time",
    "location": "US, CA, East Palo Alto",
    "locations": [
      "{\"normalizedStateName\":\"California\",\"normalizedCountryCode\":\"USA\",\"city\":\"East Palo Alto\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, CA, East Palo Alto\",\"coordinates\":\"37.4732,-122.13957\",\"normalizedCountyName\":\"San Mateo\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"East Palo Alto, California, USA\",\"location\":\"US, CA, East Palo Alto\",\"region\":\"CA\",\"buildingCodeList\":[\"SJC18\"],\"normalizedCityName\":\"East Palo Alto\"}"
    ],
    "normalized_location": "East Palo Alto, California, USA",
    "optional_search_labels": [
      "aws.team-utility-computing"
    ],
    "posted_date": "August  7, 2026",
    "preferred_qualifications": "- 3+ years of full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations experience<br/>- Bachelor's degree in computer science or equivalent<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Los Angeles County applicants: Job duties for this position include: work safely and cooperatively with other employees, supervisors, and staff; adhere to standards of excellence despite stressful conditions; communicate effectively and respectfully with employees, supervisors, and staff to ensure exceptional customer service; and follow all federal, state, and local laws and Company policies. Criminal history may have a direct, adverse, and negative relationship with some of the material job duties of this position. These include the duties and responsibilities listed above, as well as the abilities to adhere to company policies, exercise sound judgment, effectively manage stress and work safely and respectfully with others, exhibit trustworthiness and professionalism, and safeguard business operations and the Company\u2019s reputation. Pursuant to the Los Angeles County Fair Chance Ordinance, we will consider for employment qualified applicants with arrest and conviction records.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.",
    "primary_search_label": "aws.team-sde-primary",
    "source_system": "JobCreator",
    "state": "CA",
    "title": "Software Development Engineer \u2013 Big Data, AWS Elastic MapReduce (EMR), EMR EKS",
    "university_job": null,
    "updated_time": "3 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10496096/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-sde-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "210768357",
    "title": "Lead Data Engineer",
    "company": "JPMorgan Chase",
    "location": "Jersey City, NJ, United States",
    "posted_date": "2026-08-09T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210768357",
    "description_short": "Lead Data Engineer",
    "source": "JPMorgan Chase"
  },
  {
    "id": "210776665",
    "title": "Data Engineer III",
    "company": "JPMorgan Chase",
    "location": "Bengaluru, Karnataka, India",
    "posted_date": "2026-08-10T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210776665",
    "description_short": "Data Engineer III",
    "source": "JPMorgan Chase"
  }
];