window.JOBS_DATA = [
  {
    "id": "R0920565",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "5 Locations",
    "posted_date": "2026-05-22T03:51:10.078962",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/TX---Irving/Senior-Data-Engineer_R0920565",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "R0918897",
    "title": "Staff Data Engineer",
    "company": "CVS Health",
    "location": "50 Locations",
    "posted_date": "2026-05-22T03:37:04.800180",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/Farmers-Branch-4055-Valley-Vw-Ln/Staff-Data-Engineer_R0918897",
    "description_short": "Staff Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "R0920552",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "2 Locations",
    "posted_date": "2026-05-22T03:51:10.078951",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/TX---Irving/Senior-Data-Engineer_R0920552",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "R0918733",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "5 Locations",
    "posted_date": "2026-05-22T03:51:10.078955",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/TX---Irving/Senior-Data-Engineer_R0918733",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "210751058",
    "title": "Software Engineer III - Postgres, ETL, Python, AWS",
    "company": "JPMorgan Chase",
    "location": "Mumbai, Maharashtra, India",
    "posted_date": "2026-05-26T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210751058",
    "description_short": "Software Engineer III - Postgres, ETL, Python, AWS",
    "source": "JPMorgan Chase"
  },
  {
    "basic_qualifications": "- 5+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with SQL<br/>- Experience in at least one modern scripting or programming language, such as Python, Java, Scala, or NodeJS<br/>- Experience mentoring team members on best practices",
    "business_category": "aws",
    "city": "Seattle",
    "company_name": "Amazon Web Services, Inc.",
    "country_code": "USA",
    "description": "GDSP is seeking a Data Engineer to own the data infrastructure that unlocks deal intelligence and automation capabilities across the organization. The role is responsible for designing, building, and maintaining the pipelines, data models, and platforms that enable deal teams to access precise, reliable insights from broad data sets (deal telemetry, pricing models, customer usage, pipeline signals) at scale, with speed and accuracy that hold as volume grows.<br/><br/>These data products serve deal strategists, pricing leaders, and senior executives who depend on them to structure, evaluate, and negotiate transformative contracts with AWS's most strategic customers. Quality, freshness, and accuracy of data outputs have direct, measurable impact on deal velocity, pricing quality, and revenue outcomes.<br/><br/>This is a high-visibility role. The data engineer partners closely with product management to translate analytical requirements into scalable data solutions, and with engineering teams to ensure pipelines integrate cleanly across GDSP's tooling ecosystem. The role will leverage generative AI and AWS services to raise the bar on how GDSP consumes and acts on data.<br/><br/>Key job responsibilities<br/>-   Build and maintain backend data infrastructure for analytical and visualization platforms, ensuring data is clean, fresh, and optimized for downstream consumption<br/>    <br/>-   Translate business problem statements into technical data requirements, partnering with product management and stakeholders to define what data products to build<br/>    <br/>-   Automate and optimize reporting processes to enable self-service analytics at scale, reducing manual effort and improving speed to insight<br/>    <br/>-   Develop measurement frameworks and metrics that quantify deal execution performance and operational health<br/>    <br/>-   Ensure data quality through monitoring, validation, auditing, and documentation of pipelines and data sources<br/>    <br/>-   Leverage AWS services and generative AI to build next-generation data solutions that improve efficiency and unlock new analytical capabilities<br/><br/>About the team<br/>The team builds products that power how GDSP operates. Reporting and tooling that are held to the highest standards of clarity, reliability, and scalability.<br/><br/>Diverse Experiences<br/><br/>AWS values diverse experiences. Even if you do not meet all of the preferred qualifications and skills listed in the job description, we encourage candidates to apply. If your career is just starting, hasn\u2019t followed a traditional path, or includes alternative experiences, don\u2019t let it stop you from applying. <br/><br/>Why AWS?<br/><br/>Amazon Web Services (AWS) is the world\u2019s most comprehensive and broadly adopted cloud platform. We pioneered cloud computing and never stopped innovating \u2014 that\u2019s why customers from the most successful startups to Global 500 companies trust our robust suite of products and services to power their businesses.<br/><br/>Inclusive Team Culture<br/><br/>AWS values curiosity and connection. Our employee-led and company-sponsored affinity groups promote inclusion and empower our people to take pride in what makes us unique. Our inclusion events foster stronger, more collaborative teams. Our continual innovation is fueled by the bold ideas, fresh perspectives, and passionate voices our teams bring to everything we do.<br/><br/>Mentorship & Career Growth<br/><br/>We\u2019re continuously raising our performance bar as we strive to become Earth\u2019s Best Employer. That\u2019s why you\u2019ll find endless knowledge-sharing, mentorship and other career-advancing resources here to help you develop into a better-rounded professional. <br/><br/>Work/Life Balance<br/><br/>We value work-life harmony. Achieving success at work should never come at the expense of sacrifices at home, which is why we strive for flexibility as part of our working culture. When we feel supported in the workplace and at home, there\u2019s nothing we can\u2019t achieve.<br/>",
    "department_cost_center": null,
    "description_short": "GDSP is seeking a Data Engineer to own the data infrastructure that unlocks deal intelligence and automation capabilities across the organization. The role is responsible for designing, building, and maintaining",
    "display_distance": null,
    "id": "7e2ef73f-0231-4421-883e-df9a18e4a721",
    "id_icims": "10430551",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Project/Program/Product Management--Technical",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10430551/data-engineer-deal-intelligence-automation-aws-gdsp",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Texas\",\"normalizedCountryCode\":\"USA\",\"city\":\"Austin\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, TX, Austin\",\"coordinates\":\"30.26759,-97.74299\",\"normalizedCountyName\":\"Travis\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Austin, Texas, USA\",\"location\":\"US, TX, Austin\",\"region\":\"TX\",\"buildingCodeList\":[\"AUS16\"],\"normalizedCityName\":\"Austin\"}",
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA48\"],\"normalizedCityName\":\"Seattle\"}",
      "{\"normalizedStateName\":\"Virginia\",\"normalizedCountryCode\":\"USA\",\"city\":\"Arlington\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, VA, Arlington\",\"coordinates\":\"38.8905,-77.08629\",\"normalizedCountyName\":\"Arlington\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Arlington, Virginia, USA\",\"location\":\"US, VA, Arlington\",\"region\":\"VA\",\"buildingCodeList\":[\"WAS17\"],\"normalizedCityName\":\"Arlington\"}",
      "{\"normalizedStateName\":\"California\",\"normalizedCountryCode\":\"USA\",\"city\":\"Santa Monica\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, CA, Santa Monica\",\"coordinates\":\"34.01158,-118.49227\",\"normalizedCountyName\":\"Los Angeles\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Santa Monica, California, USA\",\"location\":\"US, CA, Santa Monica\",\"region\":\"CA\",\"buildingCodeList\":[\"LAX16\"],\"normalizedCityName\":\"Santa Monica\"}",
      "{\"normalizedStateName\":\"Georgia\",\"normalizedCountryCode\":\"USA\",\"city\":\"Atlanta\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, GA, Atlanta\",\"coordinates\":\"33.74831,-84.39111\",\"normalizedCountyName\":\"Fulton\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Atlanta, Georgia, USA\",\"location\":\"US, GA, Atlanta\",\"region\":\"GA\",\"buildingCodeList\":[\"ATL11\"],\"normalizedCityName\":\"Atlanta\"}",
      "{\"normalizedStateName\":\"New York\",\"normalizedCountryCode\":\"USA\",\"city\":\"New York\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, NY, New York\",\"coordinates\":\"40.71453,-74.00712\",\"normalizedCountyName\":\"New York\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"New York, New York, USA\",\"location\":\"US, NY, New York\",\"region\":\"NY\",\"buildingCodeList\":[\"JFK14\"],\"normalizedCityName\":\"New York\"}",
      "{\"normalizedStateName\":\"Virginia\",\"normalizedCountryCode\":\"USA\",\"city\":\"Herndon\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, VA, Herndon\",\"coordinates\":\"38.96973,-77.385\",\"normalizedCountyName\":\"Fairfax\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Herndon, Virginia, USA\",\"location\":\"US, VA, Herndon\",\"region\":\"VA\",\"buildingCodeList\":[\"IAD28\"],\"normalizedCityName\":\"Herndon\"}",
      "{\"normalizedStateName\":\"Illinois\",\"normalizedCountryCode\":\"USA\",\"city\":\"Chicago\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, IL, Chicago\",\"coordinates\":\"41.88425,-87.63245\",\"normalizedCountyName\":\"Cook\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Chicago, Illinois, USA\",\"location\":\"US, IL, Chicago\",\"region\":\"IL\",\"buildingCodeList\":[\"ORD11\"],\"normalizedCityName\":\"Chicago\"}",
      "{\"normalizedStateName\":\"California\",\"normalizedCountryCode\":\"USA\",\"city\":\"San Francisco\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, CA, San Francisco\",\"coordinates\":\"37.77702,-122.41956\",\"normalizedCountyName\":\"San Francisco\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"San Francisco, California, USA\",\"location\":\"US, CA, San Francisco\",\"region\":\"CA\",\"buildingCodeList\":[\"SFO28\"],\"normalizedCityName\":\"San Francisco\"}",
      "{\"normalizedStateName\":\"Texas\",\"normalizedCountryCode\":\"USA\",\"city\":\"Dallas\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, TX, Dallas\",\"coordinates\":\"32.77823,-96.7951\",\"normalizedCountyName\":\"Dallas\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Dallas, Texas, USA\",\"location\":\"US, TX, Dallas\",\"region\":\"TX\",\"buildingCodeList\":[\"DFW15\"],\"normalizedCityName\":\"Dallas\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "May 26, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience operating large data warehouses<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Los Angeles County applicants: Job duties for this position include: work safely and cooperatively with other employees, supervisors, and staff; adhere to standards of excellence despite stressful conditions; communicate effectively and respectfully with employees, supervisors, and staff to ensure exceptional customer service; and follow all federal, state, and local laws and Company policies. Criminal history may have a direct, adverse, and negative relationship with some of the material job duties of this position. These include the duties and responsibilities listed above, as well as the abilities to adhere to company policies, exercise sound judgment, effectively manage stress and work safely and respectfully with others, exhibit trustworthiness and professionalism, and safeguard business operations and the Company\u2019s reputation. Pursuant to the Los Angeles County Fair Chance Ordinance, we will consider for employment qualified applicants with arrest and conviction records.<br/><br/>Pursuant to the San Francisco Fair Chance Ordinance, we will consider for employment qualified applicants with arrest and conviction records.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, CA, San Francisco - 177,800.00 - 240,500.00 USD annually<br/>USA, CA, Santa Monica - 154,600.00 - 209,100.00 USD annually<br/>USA, GA, Atlanta - 154,600.00 - 209,100.00 USD annually<br/>USA, IL, Chicago - 154,600.00 - 209,100.00 USD annually<br/>USA, NY, New York - 170,000.00 - 230,000.00 USD annually<br/>USA, TX, Austin - 154,600.00 - 209,100.00 USD annually<br/>USA, TX, Dallas - 154,600.00 - 209,100.00 USD annually<br/>USA, VA, Arlington - 154,600.00 - 209,100.00 USD annually<br/>USA, VA, Herndon - 154,600.00 - 209,100.00 USD annually<br/>USA, WA, Seattle - 154,600.00 - 209,100.00 USD annually",
    "primary_search_label": "aws.team-product-management-primary",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, Deal Intelligence & Automation, AWS GDSP",
    "university_job": null,
    "updated_time": "3 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10430551/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-product-management-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with SQL<br/>- Experience with one or more query language (e.g., SQL, PL/SQL, DDL, MDX, HiveQL, SparkSQL, Scala)<br/>- Experience with one or more scripting language (e.g., Python, KornShell)",
    "business_category": "business-and-corporate-development",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Are you interested in using AI and data to drive the next phase of Amazon's growth?<br/><br/>Amazon Fuse (https://www.amazonfuse.com/) helps third party subscription-based businesses better serve their customers by offering the selection, convenience and value customers have come to know and love from Amazon, including millions of Prime products and our full catalog of Prime Video.<br/><br/>The Fuse Data Analytics (DA) team is looking for a Data Engineer to influence Fuse's decisions and direction using data insights. The ideal candidate is data-curious and possesses a strong analytical mindset. They excel at communicating with stakeholders and turning ambiguity and conjecture into actionable recommendations. They find opportunities where data will lead to better outcomes and mobilize the DA team to meet them.<br/><br/>In this role, you will be a technical expert with growing scope and impact. You will work with Product Managers, Software Engineers, Finance and Marketing Managers, as well as fellow Data Engineers and BI Engineers to build new data pipelines and datasets that optimize for business impact. We are seeking someone who can thrive in a fast-paced, high-energy work environment where we add value incrementally and frequently. We value highly technical people who know their subject matter deeply and are willing to learn new areas. We look for individuals who think like owners to develop themselves, their colleagues, and their team.<br/><br/>You use AI tools (e.g., coding assistants, generative AI) to accelerate pipeline development, improve code quality, and automate repetitive data engineering tasks while building and maintaining data pipelines that power AI-driven products and proactively identifying opportunities to embed AI into data workflows such as data validation, transformation logic, and documentation.<br/><br/>Key job responsibilities<br/><br/>- Architect, develop, and maintain scalable data infrastructure and data pipelines, leveraging AI tools to accelerate development and improve code quality.<br/>- Extract, transform, and load data from a variety of sources using SQL, scripting, and AWS big data technologies.<br/>- Design and implement ETL pipelines and BI solutions, identifying opportunities to embed AI into data workflows such as data validation and transformation logic.<br/>- Collaborate with business owners, SDEs, and BI Engineers to explore new data sources and deliver insights.<br/>- Stay up to date with advancements in big data and AI technologies and contribute to pilot projects.<br/>- Proactively identify and resolve data-related issues reducing operational load on the team, using AI-assisted automation where applicable.",
    "department_cost_center": null,
    "description_short": "Are you interested in using AI and data to drive the next phase of Amazon's growth?Amazon Fuse (https://www.amazonfuse.com/) helps third party subscription-based businesses better serve their customers",
    "display_distance": null,
    "id": "f8163ee2-75c0-498f-baf1-917924435986",
    "id_icims": "10430629",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Business Intelligence",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10430629/data-engineer-amazon-fuse",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA40\"],\"normalizedCityName\":\"Seattle\"}",
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"SEATTLE\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, SEATTLE\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, SEATTLE\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA40\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "May 26, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience with any ETL tool like, Informatica, ODI, SSIS, BODI, Datastage, etc.<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, SEATTLE - 101,300.00 - 160,000.00 USD annually",
    "primary_search_label": "business-and-corporate-development.team-amazon-fuse",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, Amazon Fuse",
    "university_job": null,
    "updated_time": "about 9 hours",
    "url_next_step": "https://account.amazon.jobs/jobs/10430629/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-amazon-fuse",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 5+ years of data engineering experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using ETL/ELT processes experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using OLAP technologies experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using data modeling experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using SQL experience<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "aws",
    "city": "Bellevue",
    "company_name": "Amazon Development Center U.S., Inc.",
    "country_code": "USA",
    "description": "AWS Databases, Analytics and AI/ML Products and Services is one of the largest and fast-growing business unit within AWS. We are working to rebuild and revolutionize data engineering and business intelligence systems within database, analytics and AI/ML organization to support fast growing business needs.<br/><br/>We are looking for experienced, self-driven Data Engineer. In this role, you will be building complex data engineering and business intelligence applications using AWS big data stack. You should have deep expertise and passion in working with large data sets, data visualization, building complex data processes, performance tuning, bringing data from disparate data stores and programmatically identifying patterns. You should have excellent business acumen and communication skills to be able to work with business owners to develop and define key business questions and requirements. You will provide guidance and support for other engineers with industry best practices and direction. Amazon Web Services (AWS) has culture of data-driven decision-making, and demands timely, accurate, and actionable business insights.<br/><br/>Key job responsibilities<br/>\u2022\tDesign, implement, and support data warehouse / data lake infrastructure using AWS big data stack, Python, Redshift, QuickSight, Glue/lake formation, EMR/Spark/Scala, Athena etc.<br/>\u2022\tDevelop and manage ETLs to source data from various commercial, sales and operational systems and create unified data model for analytics and reporting.<br/>\u2022\tUse business intelligence and visualization software (e.g., QuickSight.) to develop dashboards those are used by senior leadership.<br/>\u2022\tEmpower technical and non-technical, internal customers to drive their own analytics and reporting (self-serve reporting) and support ad-hoc reporting when needed.<br/>\u2022\tDevelop deep understanding of vast data sources and know exactly how, when, and which data to use to solve particular business problems.<br/>\u2022\tWork with Product Managers, Finance, Service Engineering Teams and Sales Teams on day-to-day basis to support their new analytics requirements.<br/>\u2022\tManage numerous requests concurrently and strategically, prioritizing when necessary<br/>\u2022\tPartner/collaborate across teams/roles to deliver results.<br/>\u2022\tMentor other engineers, influence positively team culture, and help grow the team.",
    "department_cost_center": null,
    "description_short": "AWS Databases, Analytics and AI/ML Products and Services is one of the largest and fast-growing business unit within AWS. We are working to rebuild and revolutionize data engineering and business intelligence",
    "display_distance": null,
    "id": "084bf0a8-92c3-42d5-84d5-a70c12381e00",
    "id_icims": "10431072",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Applied Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10431072/data-engineer-ii-dbs-bi",
    "job_schedule_type": "full-time",
    "location": "US, WA, Bellevue",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Bellevue\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Bellevue\",\"coordinates\":\"47.61001,-122.1872\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Bellevue, Washington, USA\",\"location\":\"US, WA, Bellevue\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA113\"],\"normalizedCityName\":\"Bellevue\"}"
    ],
    "normalized_location": "Bellevue, Washington, USA",
    "optional_search_labels": [
      "aws.team-utility-computing"
    ],
    "posted_date": "May 27, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Bellevue - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "aws.team-data-science-primary",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer II, DBS BI",
    "university_job": null,
    "updated_time": "3 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10431072/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-data-science-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 5+ years of data engineering experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using ETL/ELT processes experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using OLAP technologies experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using data modeling experience<br/>- 3+ years of developing and operating large-scale data structures for business intelligence analytics using SQL experience<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "aws",
    "city": "Bellevue",
    "company_name": "Amazon Development Center U.S., Inc.",
    "country_code": "USA",
    "description": "AWS Databases, Analytics and AI/ML Products and Services is one of the largest and fast-growing business unit within AWS. We are working to rebuild and revolutionize data engineering and business intelligence systems within database, analytics and AI/ML organization to support fast growing business needs.<br/><br/>We are looking for experienced, self-driven Data Engineer. In this role, you will be building complex data engineering and business intelligence applications using AWS big data stack. You should have deep expertise and passion in working with large data sets, data visualization, building complex data processes, performance tuning, bringing data from disparate data stores and programmatically identifying patterns. You should have excellent business acumen and communication skills to be able to work with business owners to develop and define key business questions and requirements. You will provide guidance and support for other engineers with industry best practices and direction. Amazon Web Services (AWS) has culture of data-driven decision-making, and demands timely, accurate, and actionable business insights.<br/><br/>Key job responsibilities<br/>\u2022\tDesign, implement, and support data warehouse / data lake infrastructure using AWS big data stack, Python, Redshift, QuickSight, Glue/lake formation, EMR/Spark/Scala, Athena etc.<br/>\u2022\tDevelop and manage ETLs to source data from various commercial, sales and operational systems and create unified data model for analytics and reporting.<br/>\u2022\tUse business intelligence and visualization software (e.g., QuickSight.) to develop dashboards those are used by senior leadership.<br/>\u2022\tEmpower technical and non-technical, internal customers to drive their own analytics and reporting (self-serve reporting) and support ad-hoc reporting when needed.<br/>\u2022\tDevelop deep understanding of vast data sources and know exactly how, when, and which data to use to solve particular business problems.<br/>\u2022\tWork with Product Managers, Finance, Service Engineering Teams and Sales Teams on day-to-day basis to support their new analytics requirements.<br/>\u2022\tManage numerous requests concurrently and strategically, prioritizing when necessary<br/>\u2022\tPartner/collaborate across teams/roles to deliver results.<br/>\u2022\tMentor other engineers, influence positively team culture, and help grow the team.",
    "department_cost_center": null,
    "description_short": "AWS Databases, Analytics and AI/ML Products and Services is one of the largest and fast-growing business unit within AWS. We are working to rebuild and revolutionize data engineering and business intelligence",
    "display_distance": null,
    "id": "5c132367-75f0-4ae6-a448-0e06d03a497d",
    "id_icims": "10431070",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Applied Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10431070/data-engineer-ii-dbs-bi",
    "job_schedule_type": "full-time",
    "location": "US, WA, Bellevue",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Bellevue\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Bellevue\",\"coordinates\":\"47.61001,-122.1872\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Bellevue, Washington, USA\",\"location\":\"US, WA, Bellevue\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA113\"],\"normalizedCityName\":\"Bellevue\"}"
    ],
    "normalized_location": "Bellevue, Washington, USA",
    "optional_search_labels": [
      "aws.team-utility-computing"
    ],
    "posted_date": "May 27, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Bellevue - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "aws.team-data-science-primary",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer II, DBS BI",
    "university_job": null,
    "updated_time": "3 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10431070/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-data-science-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Knowledge of distributed systems as it pertains to data storage and computing<br/>- Experience in at least one modern scripting or programming language, such as Python, Java, Scala, or NodeJS",
    "business_category": "aws",
    "city": "Arlington",
    "company_name": "Amazon Development Center U.S., Inc.",
    "country_code": "USA",
    "description": "Amazon  Web Services (AWS) is the world leader in providing a highly reliable, scalable, low-cost infrastructure platform in the cloud that powers  hundreds of thousands of businesses in 190 countries around the world! <br/><br/>The AWS Managed Operations (MO) organization was founded in April 2023, with the objective to reduce operational load and toil through long-term engineering projects. MO is building the best-in-class engineering and operations team that will own the day-to-day operations for AWS Regions; improving the availability, reliability, latency, performance and efficiency to operate AWS regions.<br/><br/>As a Data Engineer on the Managed Operations Intelligence (MOI) team, your technical skills and analytical mindset will be utilized designing and building some of the world's most extensive data sets, helping to craft AWS' strategic initiatives. In this role, you will collaborate with software engineering, data science, and product management teams to design/build scalable data solutions across AWS to optimize growth, strategy, and user experience across AWS. <br/><br/>This role will sit in our new headquarters in Northern Virginia, where Amazon will invest $2.5 billion dollars, occupy 4 million square feet of energy efficient office space, and create at least 25,000 new full-time jobs. Our employees and the neighboring community will also benefit from the associated investments from the Commonwealth including infrastructure updates, public transportation improvements, and new access to Reagan National Airport.<br/><br/>By working together on behalf of our customers, we are building the future one innovative product, service, and idea at a time. Are you ready to embrace the challenge? Come build the future with us.<br/><br/>This position requires that the candidate selected be a U.S. Citizen.<br/><br/>10012<br/><br/>Key job responsibilities<br/>- Collaboration and Product Development: Interact with business and software teams to understand their business requirements and operational processes, to inform system design<br/>- Data Modeling and Architecture: Develop robust data models and architectures that support the organization's data-driven initiatives, ensuring data quality, consistency, and accessibility.<br/>- Data Pipeline Development: Design, build, and maintain efficient, scalable, and reliable data pipelines to ingest, transform, and load data from various sources into a unified data platform.<br/>- Scalability and Performance: Design and implement scalable data solutions that can handle increasing data volumes and support high-performance data access and querying.<br/>- Design, provision, and maintain scalable data infrastructure on AWS (Glue, Lake Formation, S3) to support ingestion, transformation, and governance of operational data across dev, gamma, and production environments.<br/>- Documentation & Continuous Improvement: Create, enhance, and maintain technical documentation<br/><br/>A day in the life<br/>Data Engineering: Guide teams in building optimal data artifacts (datasets, visualizations) to address key questions. Refine systems, design solutions, and create scalable data models. Ensure data security and quality while suggesting efficient architecture, development approaches, and data management standards for complex analytical problems.<br/><br/>Product Leadership: Use data to identify opportunities, and tackle challenges. Ensure data artifacts/components deliver value by supporting AWS strategy and driving innovative solutions.<br/><br/>Communication and Influence: Tell data-driven stories that convince and influence partners. Build credibility with clear insights, structured recommendations, and serve as a trusted partner within the organization.<br/><br/>About the team<br/>Why AWS<br/><br/>Our team is dedicated to supporting new members. We have a broad mix of experience levels and tenures, and we\u2019re building an environment that celebrates knowledge-sharing and mentorship. Our senior members enjoy one-on-one mentoring and thorough, but kind, code reviews. We care about your career growth and strive to assign projects that help our team members develop your engineering expertise so you feel empowered to take on more complex tasks in the future.<br/><br/>Diverse Experiences<br/><br/>AWS values diverse experiences. Even if you do not meet all of the preferred qualifications and skills listed in the job description, we encourage candidates to apply. If your career is just starting, hasn\u2019t followed a traditional path, or includes alternative experiences, don\u2019t let it stop you from applying. <br/><br/>About AWS <br/><br/>Amazon Web Services (AWS) is the world\u2019s most comprehensive and broadly adopted cloud platform. We pioneered cloud computing and never stopped innovating \u2014 that\u2019s why customers from the most successful startups to Global 500 companies trust our robust suite of products and services to power their businesses.<br/><br/>AWS Infrastructure Services (AIS)<br/><br/>AWS Infrastructure Services owns the design, planning, delivery, and operation of all AWS global infrastructure. In other words, we\u2019re the people who keep the cloud running. We support all AWS data centers and all of the servers, storage, networking, power, and cooling equipment that ensure our customers have continual access to the innovation they rely on. We work on the most challenging problems, with thousands of variables impacting the supply chain \u2014 and we\u2019re looking for talented people who want to help. <br/><br/>Inclusive Team Culture<br/><br/>AWS values curiosity and connection. Our employee-led and company-sponsored affinity groups promote inclusion and empower our people to take pride in what makes us unique. Our inclusion events foster stronger, more collaborative teams. Our continual innovation is fueled by the bold ideas, fresh perspectives, and passionate voices our teams bring to everything we do.<br/><br/>Mentorship & Career Growth<br/><br/>We\u2019re continuously raising our performance bar as we strive to become Earth\u2019s Best Employer. That\u2019s why you\u2019ll find endless knowledge-sharing, mentorship and other career-advancing resources here to help you develop into a better-rounded professional. <br/><br/>Work/Life Balance<br/><br/>We value work-life harmony. Achieving success at work should never come at the expense of sacrifices at home, which is why we strive for flexibility as part of our working culture. When we feel supported in the workplace and at home, there\u2019s nothing we can\u2019t achieve in the cloud. ",
    "department_cost_center": null,
    "description_short": "Amazon  Web Services (AWS) is the world leader in providing a highly reliable, scalable, low-cost infrastructure platform in the cloud that powers  hundreds of thousands of businesses in 190 countries",
    "display_distance": null,
    "id": "18304a63-f8cf-4d2d-a6cd-a953891fd0f3",
    "id_icims": "10431035",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10431035/data-engineer-ii-managed-operations-intelligence-moi-team-data-engineering",
    "job_schedule_type": "full-time",
    "location": "US, VA, Arlington",
    "locations": [
      "{\"normalizedStateName\":\"Virginia\",\"normalizedCountryCode\":\"USA\",\"city\":\"Arlington\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, VA, Arlington\",\"coordinates\":\"38.8905,-77.08629\",\"normalizedCountyName\":\"Arlington\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Arlington, Virginia, USA\",\"location\":\"US, VA, Arlington\",\"region\":\"VA\",\"buildingCodeList\":[\"WAS17\"],\"normalizedCityName\":\"Arlington\"}"
    ],
    "normalized_location": "Arlington, Virginia, USA",
    "optional_search_labels": [
      "aws.team-region-services",
      "operations.team-data-engineering",
      "aws.team-sde-sdm",
      "arlington-hq",
      "operations.team-data-science"
    ],
    "posted_date": "May 27, 2026",
    "preferred_qualifications": "- 5+ years of data engineering experience<br/>- Experience building/operating highly available, distributed systems of data extraction, ingestion, and processing of large data sets<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/>- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, VA, Arlington - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "aws.team-data-science-primary",
    "source_system": "JobCreator",
    "state": "VA",
    "title": "Data Engineer II, Managed Operations Intelligence (MOI) Team - Data Engineering",
    "university_job": null,
    "updated_time": "about 19 hours",
    "url_next_step": "https://account.amazon.jobs/jobs/10431035/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-data-science-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "1970393556869637",
    "title": "Data Engineer II",
    "company": "Microsoft",
    "location": "United States, Multiple Locations, Multiple Locations",
    "posted_date": "2026-05-26T23:52:41",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556869637",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "basic_qualifications": "- 5+ years of non-internship professional software development experience<br/>- 5+ years of programming with at least one software programming language experience<br/>- 4+ years of leading design or architecture (design patterns, reliability and scaling) of new and existing systems experience<br/>- Experience as a mentor, tech lead or leading an engineering team",
    "business_category": "alexa-and-amazon-devices",
    "city": "Redmond",
    "company_name": "Amazon Kuiper Manufacturing Enterprises LLC",
    "country_code": "USA",
    "description": "Amazon Leo is Amazon\u2019s low Earth orbit satellite network. Our mission is to deliver fast, reliable internet connectivity to customers beyond the reach of existing networks. From individual households to schools, hospitals, businesses, and government agencies, Amazon Leo will serve people and organizations operating in locations without reliable connectivity.<br/><br/>Have you wanted an opportunity to develop the software applications and services for an advanced global telecom service? This role of for a Senior Software Engineer who will lead the design, implementation, and operations of globally available distributed systems geared towards, managing, and monitoring Leo's terrestrial devices. You\u2019ll build systems using the latest AWS technologies, leveraging best-in-industry software engineering practices.<br/><br/>Export Control Requirement:<br/>Due to applicable export control laws and regulations, candidates must be a U.S. citizen or national, U.S. permanent resident (i.e., current Green Card holder), or lawfully admitted into the U.S. as a refugee or granted asylum.<br/><br/>Key job responsibilities<br/>JOB RESPONSIBILITIES<br/> \u00b7 Design and implement Telecom Applications and Services.<br/> \u00b7 Partner with the Satellite, Networks and Security engineering teams.<br/> \u00b7 Drive Customer Engagement Systems application and data architecture.<br/>\u00b7 Evangelize engineering excellence best practices and mentor junior engineers.<br/><br/>About the team<br/>Leo Data Platform team build services to ingest, transform, and aggregate data from various devices in Leo Network, and auto detect, diagnose, and resolve issues. We use ML technology to monitor customer experience and prevent fraud and abuse.",
    "department_cost_center": null,
    "description_short": "Amazon Leo is Amazon\u2019s low Earth orbit satellite network. Our mission is to deliver fast, reliable internet connectivity to customers beyond the reach of existing networks. From individual households to",
    "display_distance": null,
    "id": "f72ede29-5af9-496c-9581-88ba9d7cc936",
    "id_icims": "10432316",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Software Development",
    "job_function_id": null,
    "job_path": "/en/jobs/10432316/software-development-engineer-leo-data-platform",
    "job_schedule_type": "full-time",
    "location": "US, WA, Redmond",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Redmond\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Redmond\",\"coordinates\":\"47.67858,-122.13158\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Redmond, Washington, USA\",\"location\":\"US, WA, Redmond\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA114\"],\"normalizedCityName\":\"Redmond\"}"
    ],
    "normalized_location": "Redmond, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "May 27, 2026",
    "preferred_qualifications": "- 5+ years of full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations experience<br/>- Bachelor's degree in computer science or equivalent<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Redmond - 168,100.00 - 227,400.00 USD annually",
    "primary_search_label": "alexa-and-amazon-devices.team-project-kuiper",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Software Development Engineer, Leo Data Platform",
    "university_job": null,
    "updated_time": "2 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10432316/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-project-kuiper",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 5+ years of non-internship professional software development experience<br/>- 5+ years of programming with at least one software programming language experience<br/>- 4+ years of leading design or architecture (design patterns, reliability and scaling) of new and existing systems experience<br/>- Experience as a mentor, tech lead or leading an engineering team",
    "business_category": "alexa-and-amazon-devices",
    "city": "Redmond",
    "company_name": "Amazon Kuiper Manufacturing Enterprises LLC",
    "country_code": "USA",
    "description": "Amazon Leo is Amazon\u2019s low Earth orbit satellite network. Our mission is to deliver fast, reliable internet connectivity to customers beyond the reach of existing networks. From individual households to schools, hospitals, businesses, and government agencies, Amazon Leo will serve people and organizations operating in locations without reliable connectivity.<br/><br/>Have you wanted an opportunity to develop the software applications and services for an advanced global telecom service? This role of for a Senior Software Engineer who will lead the design, implementation, and operations of globally available distributed systems geared towards, managing, and monitoring Leo's terrestrial devices. You\u2019ll build systems using the latest AWS technologies, leveraging best-in-industry software engineering practices.<br/><br/>Export Control Requirement:<br/>Due to applicable export control laws and regulations, candidates must be a U.S. citizen or national, U.S. permanent resident (i.e., current Green Card holder), or lawfully admitted into the U.S. as a refugee or granted asylum.<br/><br/>Key job responsibilities<br/>JOB RESPONSIBILITIES<br/> \u00b7 Design and implement Telecom Applications and Services.<br/> \u00b7 Partner with the Satellite, Networks and Security engineering teams.<br/> \u00b7 Drive Customer Engagement Systems application and data architecture.<br/>\u00b7 Evangelize engineering excellence best practices and mentor junior engineers.<br/><br/>About the team<br/>Leo Data Platform team build services to ingest, transform, and aggregate data from various devices in Leo Network, and auto detect, diagnose, and resolve issues. We use ML technology to monitor customer experience and prevent fraud and abuse.",
    "department_cost_center": null,
    "description_short": "Amazon Leo is Amazon\u2019s low Earth orbit satellite network. Our mission is to deliver fast, reliable internet connectivity to customers beyond the reach of existing networks. From individual households to",
    "display_distance": null,
    "id": "1363da2b-9b5b-4677-a548-fe115e42fabd",
    "id_icims": "10432317",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Software Development",
    "job_function_id": null,
    "job_path": "/en/jobs/10432317/software-development-engineer-leo-data-platform",
    "job_schedule_type": "full-time",
    "location": "US, WA, Redmond",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Redmond\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Redmond\",\"coordinates\":\"47.67858,-122.13158\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Redmond, Washington, USA\",\"location\":\"US, WA, Redmond\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA114\"],\"normalizedCityName\":\"Redmond\"}"
    ],
    "normalized_location": "Redmond, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "May 27, 2026",
    "preferred_qualifications": "- 5+ years of full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations experience<br/>- Bachelor's degree in computer science or equivalent<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Redmond - 168,100.00 - 227,400.00 USD annually",
    "primary_search_label": "alexa-and-amazon-devices.team-project-kuiper",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Software Development Engineer, Leo Data Platform",
    "university_job": null,
    "updated_time": "2 days",
    "url_next_step": "https://account.amazon.jobs/jobs/10432317/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-project-kuiper",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "R0790710",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "50 Locations",
    "posted_date": "2026-05-28T03:37:21.375924",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/Work-At-Home-Illinois/Sr-Data-Engineer_R0790710",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using ETL/ELT processes experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using OLAP technologies experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using data modeling experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using SQL experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using Oracle experience<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "north-america-stores",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "WW Pricing drives the success of Amazon Retail and 3P Pricing. We build software that makes billions of monthly pricing recommendations on our marketplaces. We earn our customers' trust by consistently delivering the lowest prices possible: we price and publish prices automatically for the millions of products bought worldwide every day by our customers.<br/><br/>You will be joining WW Pricing Data & Analytics team which consists of several Data Engineers and Business Intelligence Engineers.<br/><br/>As a Data Engineer, you will create data models and ML data infrastructure that power our pricing algorithms and shape both customer and seller experiences. You'll develop essential data flows that keep our systems running smoothly while uncovering valuable insights that drive customer and seller success. You'll be developing GenAI based solutions to improve the operational and reporting efficiency.<br/><br/>This job is for you if you are passionate about working with the largest and most complex data to optimize service performance. You will own the models and processes for collecting and transforming data, and work within the Pricing software engineering teams to drive the resulting business initiatives. You will learn the customer's intentions, and support us in understanding them as we take our business to the next level.<br/><br/><br/>Key job responsibilities<br/>- Architecture design and implementation of next generation data pipelines and BI solutions<br/>- Manage AWS resources including EC2, RDS, Redshift, Kinesis, EMR, Lambda etc.<br/>- Build and deliver high quality data architecture and pipelines to support business analyst, data scientists, and customer reporting needs.<br/>- Interface with other technology teams to extract, transform, and load data from a wide variety of data sources<br/>- Continually improve ongoing reporting and analysis processes, automating or simplifying self-service support for customers",
    "department_cost_center": null,
    "description_short": "WW Pricing drives the success of Amazon Retail and 3P Pricing. We build software that makes billions of monthly pricing recommendations on our marketplaces. We earn our customers' trust by consistently",
    "display_distance": null,
    "id": "d08b622b-b84d-42a4-9538-7128025d2c66",
    "id_icims": "10433467",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10433467/data-engineer-ww-pricing-data-analytics",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA71\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "May 28, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Seattle - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "north-america-stores.pricing",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, WW Pricing - Data & Analytics",
    "university_job": null,
    "updated_time": "about 2 hours",
    "url_next_step": "https://account.amazon.jobs/jobs/10433467/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "pricing",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with one or more query language (e.g., SQL, PL/SQL, DDL, MDX, HiveQL, SparkSQL, Scala)<br/>- Experience with one or more scripting language (e.g., Python, KornShell)",
    "business_category": "north-america-stores",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "WW Pricing drives the success of Amazon Retail and 3P Pricing. We build software that makes billions of monthly pricing recommendations on our marketplaces. We earn our customers' trust by consistently delivering the lowest prices possible: we price and publish prices automatically for the millions of products bought worldwide every day by our customers.<br/><br/>You will be joining WW Pricing Data & Analytics team which consists of several Data Engineers and Business Intelligence Engineers.<br/><br/>As a Data Engineer, you will create data models and ML data infrastructure that power our pricing algorithms and shape both customer and seller experiences. You'll develop essential data flows that keep our systems running smoothly while uncovering valuable insights that drive customer and seller success. You'll be developing GenAI based solutions to improve the operational and reporting efficiency.<br/><br/>This job is for you if you are passionate about working with the largest and most complex data to optimize service performance. You will own the models and processes for collecting and transforming data, and work within the Pricing software engineering teams to drive the resulting business initiatives. You will learn the customer's intentions, and support us in understanding them as we take our business to the next level.<br/><br/>Key job responsibilities<br/>- SQL proficiency (Redshift, Athena, Spark SQL)<br/>- Experience with at least one programming language (Python, Java, or Scala)<br/>- Familiarity with distributed data processing frameworks (Spark, EMR)<br/>- Understanding of data warehousing concepts and star/snowflake schemas",
    "department_cost_center": null,
    "description_short": "WW Pricing drives the success of Amazon Retail and 3P Pricing. We build software that makes billions of monthly pricing recommendations on our marketplaces. We earn our customers' trust by consistently",
    "display_distance": null,
    "id": "84501635-6653-4bbb-8a93-08acd80f06b8",
    "id_icims": "10433430",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/10433430/data-engineer-ww-pricing-data-analytics",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA71\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "May 28, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Seattle - 101,300.00 - 160,000.00 USD annually",
    "primary_search_label": "north-america-stores.pricing",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, WW Pricing - Data & Analytics",
    "university_job": null,
    "updated_time": "about 22 hours",
    "url_next_step": "https://account.amazon.jobs/jobs/10433430/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "pricing",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "1970393556868981",
    "title": "Data Engineer II",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-05-28T18:44:22",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556868981",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "basic_qualifications": "- 3+ years of non-internship professional software development experience<br/>- 3+ years of non-internship design or architecture (design patterns, reliability and scaling) of new and existing systems experience<br/>- 3+ years of designing and developing large-scale, multi-tiered, multi-threaded, embedded or distributed software applications, tools, systems, and services using: C#, C++, Java, or Perl experience<br/>- 3+ years of programming using a modern programming language such as Java, C++, or C#, including object-oriented design experience<br/>- 3+ years of big data technologies such as AWS, Hadoop, Spark, Pig, Hive, Lucene/SOLR or Storm/Samza experience",
    "business_category": "entertainment",
    "city": "New York",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Prime Video is a first-stop entertainment destination offering customers a vast collection of premium programming in one app available across thousands of devices. Prime members can customize their viewing experience and find their favorite movies, series, documentaries, and live sports \u2013 including Amazon MGM Studios-produced series and movies; licensed fan favorites; and programming from Prime Video add-on subscriptions such as Apple TV+, Max, Crunchyroll and MGM+. All customers, regardless of whether they have a Prime membership or not, can rent or buy titles via the Prime Video Store, and can enjoy even more content for free with ads.<br/><br/>Are you interested in shaping the future of entertainment? Prime Video's technology teams are creating best-in-class digital video experience.<br/><br/>As a Prime Video technologist, you\u2019ll have end-to-end ownership of the product, user experience, design, and technology required to deliver state-of-the-art experiences for our customers. You\u2019ll get to work on projects that are fast-paced, challenging, and varied. You\u2019ll also be able to experiment with new possibilities, take risks, and collaborate with remarkable people.<br/><br/>We are looking for a self-motivated, passionate and resourceful Software Development Engineer to bring diverse perspectives, ideas, and skill-sets to make Prime Video even better for our customers. You will be a technical leader helping to design and build the data & machine learning infrastructure that powers our vision. You will tackle complex and ambiguous problems, designing and delivering scalable and resilient platform solutions from the ground up. You will not only write high-quality, maintainable code, but also mentor other engineers, influence our technical strategy, and drive engineering best practices across the team. Your work will directly contribute to making Prime Video's operations more efficient and will set the technical foundation for years to come.<br/><br/>Key job responsibilities<br/>As a SDE on the Prime Video Data Platform team, you will have subject matter expertise in the areas of big data pipeline architecture, data foundations for personalization & recommendation systems and world-class user experience for customers of our data & ML infrastructure offerings. You will work with teams of scientists, product managers and engineers to translate business and functional requirements into concrete system deliverables. You will have the opportunity to build new platform services from the ground up, driving the development of innovative approaches to personalization, and providing opportunities for scientists and engineers to invent and implement scalable ML solutions supporting new customer experiences.",
    "department_cost_center": null,
    "description_short": "Prime Video is a first-stop entertainment destination offering customers a vast collection of premium programming in one app available across thousands of devices. Prime members can customize their viewing",
    "display_distance": null,
    "id": "d3e103ab-d6ef-4ac5-8755-69fd7dae1196",
    "id_icims": "10434159",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Software Development",
    "job_function_id": null,
    "job_path": "/en/jobs/10434159/software-development-engineer-data-platform-prime-video-personalization-discovery",
    "job_schedule_type": "full-time",
    "location": "US, NY, New York",
    "locations": [
      "{\"normalizedStateName\":\"California\",\"normalizedCountryCode\":\"USA\",\"city\":\"Sunnyvale\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, CA, Sunnyvale\",\"coordinates\":\"37.37188,-122.03751\",\"normalizedCountyName\":\"Santa Clara\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Sunnyvale, California, USA\",\"location\":\"US, CA, Sunnyvale\",\"region\":\"CA\",\"buildingCodeList\":[\"SJC13\"],\"normalizedCityName\":\"Sunnyvale\"}",
      "{\"normalizedStateName\":\"New York\",\"normalizedCountryCode\":\"USA\",\"city\":\"New York\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, NY, New York\",\"coordinates\":\"40.71453,-74.00712\",\"normalizedCountyName\":\"New York\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"New York, New York, USA\",\"location\":\"US, NY, New York\",\"region\":\"NY\",\"buildingCodeList\":[\"JFK24\"],\"normalizedCityName\":\"New York\"}",
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"SEATTLE\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, SEATTLE\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, SEATTLE\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA40\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "New York, New York, USA",
    "optional_search_labels": [
      "amazon.artificial-intelligence",
      "primevideo.team-tech"
    ],
    "posted_date": "May 29, 2026",
    "preferred_qualifications": "- 3+ years of full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations experience<br/>- Experience contributing to the architecture and design (architecture, design patterns, reliability and scaling) of new and current systems<br/>- Bachelor's degree in computer science or equivalent<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Los Angeles County applicants: Job duties for this position include: work safely and cooperatively with other employees, supervisors, and staff; adhere to standards of excellence despite stressful conditions; communicate effectively and respectfully with employees, supervisors, and staff to ensure exceptional customer service; and follow all federal, state, and local laws and Company policies. Criminal history may have a direct, adverse, and negative relationship with some of the material job duties of this position. These include the duties and responsibilities listed above, as well as the abilities to adhere to company policies, exercise sound judgment, effectively manage stress and work safely and respectfully with others, exhibit trustworthiness and professionalism, and safeguard business operations and the Company\u2019s reputation. Pursuant to the Los Angeles County Fair Chance Ordinance, we will consider for employment qualified applicants with arrest and conviction records.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, CA, Sunnyvale - 165,200.00 - 223,600.00 USD annually<br/>USA, NY, New York - 158,100.00 - 213,800.00 USD annually<br/>USA, WA, SEATTLE - 143,700.00 - 194,400.00 USD annually",
    "primary_search_label": "entertainment.team-primevideo",
    "source_system": "JobCreator",
    "state": "NY",
    "title": "Software Development Engineer,  Data Platform, Prime Video Personalization & Discovery",
    "university_job": null,
    "updated_time": "about 16 hours",
    "url_next_step": "https://account.amazon.jobs/jobs/10434159/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-primevideo",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "R0781016-1",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "MA - Wellesley",
    "posted_date": "2026-05-29T15:31:48.346267",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/MA---Wellesley/Senior-Data-Engineer_R0781016-1",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  }
];