window.JOBS_DATA = [
  {
    "id": "R0718866-1",
    "title": "Senior Data Engineer (Platform Engineering)",
    "company": "CVS Health",
    "location": "50 Locations",
    "posted_date": "2026-02-18T07:02:12.169120",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/Treehouse/Senior-Platform-Engineer_R0718866-1",
    "description_short": "Senior Data Engineer (Platform Engineering)",
    "source": "CVS Health"
  },
  {
    "id": "R0813114",
    "title": "Senior Data Engineer",
    "company": "CVS Health",
    "location": "PA - Work from home",
    "posted_date": "2026-02-12T02:22:42.005514",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/PA---Work-from-home/Senior-Data-Engineer_R0813114",
    "description_short": "Senior Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "1970393556638740",
    "title": "Data Engineer",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-02-10T22:51:41",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556638740",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "1970393556630984",
    "title": "Member of Technical Staff - Data Engineer",
    "company": "Microsoft",
    "location": "United States, New York, New York",
    "posted_date": "2026-02-10T20:53:21",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556630984",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "210710749",
    "title": "Data Engineer II",
    "company": "JPMorgan Chase",
    "location": "Bengaluru, Karnataka, India",
    "posted_date": "2026-02-11T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210710749",
    "description_short": "Data Engineer II",
    "source": "JPMorgan Chase"
  },
  {
    "id": "1970393556752798",
    "title": "Principle Data Platform Engineer",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-02-11T17:16:02",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556752798",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "basic_qualifications": "- 3+ years of non-internship professional software development experience<br/>- 2+ years of non-internship design or architecture (design patterns, reliability and scaling) of new and existing systems experience<br/>- Experience programming with at least one software programming language<br/>- Experience designing or architecting (design patterns, reliability and scaling) of new and existing systems",
    "business_category": "advertising",
    "city": "New York",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Are you passionate about Big Data, Distributed systems, and designing new state-of-the-art AI agent-friendly data interfaces?  Be part of a team of world-class engineers and industry leading experts operating one of the largest big data platforms for advertising at Amazon scale.<br/><br/><br/>Key job responsibilities<br/>Join our team and take ownership of significant initiatives that solve some of the toughest technical challenges in big data:<br/><br/>- Design and build highly scalable, fault-tolerant data pipelines processing petabytes of advertising data<br/>- Architect new data paradigms that enable real-time analytics and machine learning applications<br/>- Collaborate with data scientists, product managers, and partner teams across Amazon Ads to deliver data solutions that drive business impact<br/>- Mentor junior engineers through code reviews, design discussions, and pair programming<br/>- Contribute to technical strategy and architectural decisions for our data platform<br/>- Build monitoring, alerting, and data quality frameworks to ensure reliability at scale<br/>Our systems are built for stability and reliability, which means our on-call shifts are manageable and focused on continuous improvement rather than firefighting.<br/><br/>About the team<br/>We're a collaborative team of 12 engineers who are passionate about solving complex data challenges while maintaining a healthy work-life balance. Our engineers regularly work with latest technologies\u2014recent projects include migrating our data lake to Apache Iceberg, implementing real-time streaming pipelines with Spark, and building unified and flexible reporting solutions. We invest heavily in your growth through mentorship programs, technical design reviews, and opportunities to present at internal tech talks. We believe in sustainable engineering practices with reasonable on-call rotations (typically one week per quarter) and flexible work arrangements.",
    "department_cost_center": null,
    "description_short": "Are you passionate about Big Data, Distributed systems, and designing new state-of-the-art AI agent-friendly data interfaces?  Be part of a team of world-class engineers and industry leading experts operating",
    "display_distance": null,
    "id": "6359907a-1a70-4b3b-a157-cd71ac97f81a",
    "id_icims": "3179173",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Software Development",
    "job_family": "Software Development",
    "job_function_id": null,
    "job_path": "/en/jobs/3179173/software-development-engineer-big-data-brand-metrics-and-benchmarks",
    "job_schedule_type": "full-time",
    "location": "US, NY, New York",
    "locations": [
      "{\"normalizedStateName\":\"New York\",\"normalizedCountryCode\":\"USA\",\"city\":\"New York\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, NY, New York\",\"coordinates\":\"40.71453,-74.00712\",\"normalizedCountyName\":\"New York\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"New York, New York, USA\",\"location\":\"US, NY, New York\",\"region\":\"NY\",\"buildingCodeList\":[\"JFK24\"],\"normalizedCityName\":\"New York\"}"
    ],
    "normalized_location": "New York, New York, USA",
    "optional_search_labels": [
      "advertising.team-software-development"
    ],
    "posted_date": "February 11, 2026",
    "preferred_qualifications": "- 4+ years of full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations experience<br/>- Experience leading engineering teams as a mentor or tech lead<br/>- Experience with big data technologies such as AWS, Hadoop, Spark, Pig, Hive etc.<br/>- Experience operating highly available, distributed systems of data extraction, ingestion, and processing of large data sets, or experience with data infrastructures: Elastic-Search, and Big Data EMR/S3/Glue/Lambda/Apache Iceberg.<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, NY, New York - 158,100.00 - 213,800.00 USD annually",
    "primary_search_label": "advertising.team-amazon-ads",
    "source_system": "JobCreator",
    "state": "NY",
    "title": "Software Development Engineer - Big Data, Brand Metrics and Benchmarks",
    "university_job": null,
    "updated_time": "6 days",
    "url_next_step": "https://account.amazon.com/jobs/3179173/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-amazon-ads",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "210686298",
    "title": "Data Engineer III - AWS / Databricks",
    "company": "JPMorgan Chase",
    "location": "Plano, TX, United States",
    "posted_date": "2026-02-11T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210686298",
    "description_short": "Data Engineer III - AWS / Databricks",
    "source": "JPMorgan Chase"
  },
  {
    "id": "1970393556619586",
    "title": "Senior Data Engineer",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-02-12T17:08:21",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556619586",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "R0822616",
    "title": "Data Engineer",
    "company": "CVS Health",
    "location": "TX - Richardson",
    "posted_date": "2026-02-12T13:01:22.701195",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/TX---Richardson/Data-Engineer_R0822616",
    "description_short": "Data Engineer",
    "source": "CVS Health"
  },
  {
    "id": "210711474",
    "title": "Data Engineer III - SQL, ETL and Analytics",
    "company": "JPMorgan Chase",
    "location": "GLASGOW, LANARKSHIRE, United Kingdom",
    "posted_date": "2026-02-12T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210711474",
    "description_short": "Data Engineer III - SQL, ETL and Analytics",
    "source": "JPMorgan Chase"
  },
  {
    "id": "210711477",
    "title": "Data Engineer II - SQL,ETL and Analytics",
    "company": "JPMorgan Chase",
    "location": "GLASGOW, LANARKSHIRE, United Kingdom",
    "posted_date": "2026-02-12T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210711477",
    "description_short": "Data Engineer II - SQL,ETL and Analytics",
    "source": "JPMorgan Chase"
  },
  {
    "id": "210710602",
    "title": "Lead Data Engineer - Data Platform",
    "company": "JPMorgan Chase",
    "location": "LONDON, LONDON, United Kingdom",
    "posted_date": "2026-02-13T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210710602",
    "description_short": "Lead Data Engineer - Data Platform",
    "source": "JPMorgan Chase"
  },
  {
    "basic_qualifications": "- 5+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with SQL<br/>- Experience in at least one modern scripting or programming language, such as Python, Java, Scala, or NodeJS<br/>- Bachelor's degree in Computer Science, Computer Engineering, Information Technology, or related fields",
    "business_category": "aws",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "AWS Infrastructure Services owns the design, planning, delivery, and operation of all AWS global infrastructure. In other words, we\u2019re the people who keep the cloud running. We support all AWS data centers and all of the servers, storage, networking, power, and cooling equipment that ensure our customers have continual access to the innovation they rely on. We work on the most challenging problems, with thousands of variables impacting the supply chain \u2014 and we\u2019re looking for talented people who want to help. <br/> <br/>You\u2019ll join a diverse team of software, hardware, and network engineers, supply chain specialists, security experts, operations managers, and other vital roles. You\u2019ll collaborate with people across AWS to help us deliver the highest standards for safety and security while providing seemingly infinite capacity at the lowest possible cost for our customers. You\u2019ll experience an inclusive culture that welcomes bold ideas and empowers you to own them to completion.<br/><br/>We\u2019re looking for Senior Data Engineer to help us grow our Data Lake and Data Warehouse Systems, which is being built using a serverless architecture, with 100% native AWS components including Redshift Spectrum, Athena, S3, Lambda, Glue, EMR, Kinesis, SNS, CloudWatch and more! We own a world-class data lake that is used to drive multi-billion dollar decisions on a regular cadence and we're looking to improve on filling the lake quickly, with as little human intervention needed and democratize the data in the lake.<br/><br/>Our Data Engineers build the ETL and analytics solutions for our internal customers to answer questions with data and drive critical improvements for the business. Our Data Engineers use best practices in software engineering, data management, data storage, data compute, and distributed systems. We are passionate about solving business problems with data!<br/><br/><br/><br/>Key job responsibilities<br/> - Develop and maintain automated ETL pipelines (with monitoring) using scripting languages such as Python, Spark, SQL and AWS services such as S3, Glue, Lambda, SNS, SQS, KMS. <br/> - Implement and support reporting and analytics infrastructure for internal business customers.<br/> - Develop and maintain data security and permissions solutions for enterprise scale data warehouse and data lake implementations including data encryption and database user access controls and logging.<br/> - Develop data objects for business analytics using data modeling techniques. <br/> - Develop and optimize data warehouse and data lake tables using best practices for DDL, physical and logical tables, data partitioning, compression, and parallelization.<br/> - Develop and maintain data warehouse and data lake metadata, data catalog, and user documentation for internal business customers.<br/> - Work with internal business customers and software development teams to gather and document requirements for data publishing and data consumption via data warehouse, data lake, and analytics solutions.<br/><br/><br/>About the team<br/>About AWS<br/><br/>Diverse Experiences<br/>AWS values diverse experiences. Even if you do not meet all of the qualifications and skills listed in the job description, we encourage candidates to apply. If your career is just starting, hasn\u2019t followed a traditional path, or includes alternative experiences, don\u2019t let it stop you from applying.<br/><br/>Why AWS?<br/>Amazon Web Services (AWS) is the world\u2019s most comprehensive and broadly adopted cloud platform. We pioneered cloud computing and never stopped innovating \u2014 that\u2019s why customers from the most successful startups to Global 500 companies trust our robust suite of products and services to power their businesses.<br/><br/>Inclusive Team Culture<br/>Here at AWS, it\u2019s in our nature to learn and be curious. Our employee-led affinity groups foster a culture of inclusion that empower us to be proud of our differences. Ongoing events and learning experiences, including our Conversations on Race and Ethnicity (CORE), inspire us to never stop embracing our uniqueness.<br/><br/>Mentorship & Career Growth<br/>We\u2019re continuously raising our performance bar as we strive to become Earth\u2019s Best Employer. That\u2019s why you\u2019ll find endless knowledge-sharing, mentorship and other career-advancing resources here to help you develop into a better-rounded professional.<br/><br/>Work/Life Balance<br/>We value work-life harmony. Achieving success at work should never come at the expense of sacrifices at home, which is why we strive for flexibility as part of our working culture. When we feel supported in the workplace and at home, there\u2019s nothing we can\u2019t achieve in the cloud.",
    "department_cost_center": null,
    "description_short": "AWS Infrastructure Services owns the design, planning, delivery, and operation of all AWS global infrastructure. In other words, we\u2019re the people who keep the cloud running. We support all AWS data centers",
    "display_distance": null,
    "id": "38d6dc7a-cc78-4780-a022-3042a2332e20",
    "id_icims": "3181333",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Business Intelligence",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/3181333/senior-data-engineer-aws-infrastructure-supply-chain-automation",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA84\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [
      "aws.team-supply-chain",
      "aws.team-adc-infra-optional",
      "aws.team-ais"
    ],
    "posted_date": "February 13, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience operating large data warehouses<br/>- Experience coaching managers and supervisors to use company best practices for maximum effectiveness<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Seattle - 154,600.00 - 209,100.00 USD annually",
    "primary_search_label": "aws.team-data-science-primary",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Senior Data Engineer, AWS Infrastructure Supply Chain Automation",
    "university_job": null,
    "updated_time": "4 days",
    "url_next_step": "https://account.amazon.com/jobs/3181333/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-data-science-primary",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 5+ years of data engineering experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using ETL/ELT processes experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using OLAP technologies experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using data modeling experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using SQL experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using Oracle experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience working on and delivering end to end projects independently",
    "business_category": "finance",
    "city": "Seattle",
    "company_name": "Amazon.com LLC",
    "country_code": "USA",
    "description": "The International stores Finance Central tech team is looking for a passionate and solution oriented Data Engineering for designing and implementing the complex ETL pipelines and analytics solutions to support the rapidly growing and dynamic business demand for data, and use it to deliver the data as service which will have an immediate influence on day-to-day decision making at Amazon<br/><br/>We are seeking a strong, experienced Data Engineering who will lead the technical design, development and launch of a new global system that will serve finance needs worldwide. Their technical skill set will deliver a new system and services that will be at the core of making it easier for customers to do business with Amazon Retail. A strong candidate will have experience with designing and building secure, distributed systems that operate globally. They will have experience in building on AWS, and be responsible for the architecture, design and implementation that will provide availability, and latency guarantees. Finally, they will be leaders on the team, and will raise the bar for the organization by mentoring junior engineers, interviewing and setting a high bar for coding standards. <br/><br/>Key job responsibilities<br/>5+ years as a Data Engineer or in a similar role<br/>Experience with data modeling, data warehousing, and building ETL pipelines<br/>Experience leading and influencing the data strategy of your team or organization<br/>Experience in SQL<br/>A Bachelor's degree in Computer Science or similar major<br/>Hands-on experience leading delivery and operations of distributed, high quality systems<br/>Fundamentals in data structures, algorithm, problem solving, and complexity analysis",
    "department_cost_center": null,
    "description_short": "The International stores Finance Central tech team is looking for a passionate and solution oriented Data Engineering for designing and implementing the complex ETL pipelines and analytics solutions to",
    "display_distance": null,
    "id": "30810f60-1c94-49a8-a132-e7db5f2d639f",
    "id_icims": "3181025",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Database Administration",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/3181025/data-engineer-ii-isf-central-tech-team",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA27\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [],
    "posted_date": "February 13, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/>- Experience with explainable machine learning and artificial intelligence methodologies and tools<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Seattle - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "finance.team-consumer",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer II, ISF Central Tech Team",
    "university_job": null,
    "updated_time": "4 days",
    "url_next_step": "https://account.amazon.com/jobs/3181025/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-consumer",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "1970393556754190",
    "title": "Data Engineering- Compromise & Fraud Prevention",
    "company": "Microsoft",
    "location": "United States, Washington, Redmond",
    "posted_date": "2026-02-13T19:50:52",
    "url_next_step": "https://jobs.careers.microsoft.com/global/en/job/1970393556754190",
    "description_short": "...",
    "source": "Microsoft"
  },
  {
    "id": "210712430",
    "title": "Data Engineer II, Glass Liquidity and Cash Management",
    "company": "JPMorgan Chase",
    "location": "Singapore",
    "posted_date": "2026-02-13T00:00:00",
    "url_next_step": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210712430",
    "description_short": "Data Engineer II, Glass Liquidity and Cash Management",
    "source": "JPMorgan Chase"
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- 4+ years of SQL experience<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "finance",
    "city": "Dallas",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Do you have the technical chops to build BI solutions that process  billions of rows a day using AWS technologies? Do you want to create  next-generation tools for intuitive data access? Do you wake up in the  middle of the night with new ideas that will benefit your customers? Are  you persistent in bringing your ideas to fruition?<br/><br/>In this role, you will have the opportunity to help shape and deliver on a strategy to build PFS using Amazon\u2019s utility computing web services (Amazon EC2 compute, Amazon S3 storage, Amazon Simple DB/RDS databases, Amazon CloudFront, etc.) . You will partner with accounting and tax stakeholders and will strive to earn their trust. You will work directly with your customers and will constantly innovate on their behalf. You will be a great negotiator and enjoy working with diverse mindsets.<br/><br/>Key job responsibilities<br/>First things  first, you know SQL and data modeling like the back of your hand. You need to know data relationships, whether relational, non-relational, streams, json, xml etc. and the best way to deal with these. You have a history of coming  up with innovative solutions to complex technical problems. You are a  quick and willing learner of new technologies and have examples to prove  your aptitude. You are not tool-centric; you determine what technology  works best for the problem at hand and apply it accordingly. You can  explain complex concepts to your non-technical customers in simple  terms.<br/><br/>In this role you will be responsible for creating finance systems that support Amazon's global footprint. You should insist on the highest standards for quality, maintainability, and performance. The systems we own are responsible for trillions of financial events that would rank among the largest countries in the world by GDP. You will ensure that engineering best practices are followed and that software is designed to be highly-available, dynamically scalable, and resilient to continuity threats.<br/><br/>As a technology leader, you will drive architectural and design choices and invent new features. We have a team culture that encourages innovation with a high level of ownership for the product vision, technical architecture and project delivery. Successful candidates will be high-bandwidth leaders who can cut through the noise, simplify relentlessly, deliver results, and build great customer experience.<br/><br/>A day in the life<br/><br/><br/>",
    "department_cost_center": null,
    "description_short": "Do you have the technical chops to build BI solutions that process  billions of rows a day using AWS technologies? Do you want to create  next-generation tools for intuitive data access? Do you wake up",
    "display_distance": null,
    "id": "4819b3af-413f-49ad-a2f3-2061108d84b2",
    "id_icims": "3183014",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Business Intelligence",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/3183014/data-engineer-project-accounting",
    "job_schedule_type": "full-time",
    "location": "US, TX, Dallas",
    "locations": [
      "{\"normalizedStateName\":\"Texas\",\"normalizedCountryCode\":\"USA\",\"city\":\"Dallas\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, TX, Dallas\",\"coordinates\":\"32.77823,-96.7951\",\"normalizedCountyName\":\"Dallas\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Dallas, Texas, USA\",\"location\":\"US, TX, Dallas\",\"region\":\"TX\",\"buildingCodeList\":[\"DFW11\"],\"normalizedCityName\":\"Dallas\"}"
    ],
    "normalized_location": "Dallas, Texas, USA",
    "optional_search_labels": [],
    "posted_date": "February 17, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, TX, Dallas - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "finance.team-fintech",
    "source_system": "JobCreator",
    "state": "TX",
    "title": "Data Engineer, Project Accounting",
    "university_job": null,
    "updated_time": "about 12 hours",
    "url_next_step": "https://account.amazon.com/jobs/3183014/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-fintech",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 3+ years of data engineering experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using ETL/ELT processes experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using OLAP technologies experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using data modeling experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using SQL experience<br/>- 1+ years of developing and operating large-scale data structures for business intelligence analytics using Oracle experience<br/>- Experience with data modeling, warehousing and building ETL pipelines",
    "business_category": "amazonian-experience-and-tech",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Are you driven by the excitement of unraveling intricate data puzzles? Does your DNA resonate with collaborative problem-solving? Do you thrive on witnessing the ripple effects of your contributions in the larger scheme of things? If you've nodded along to any of these questions, welcome to Amazon PeopleInsights eXperience (APIX) team! We're not just a team; we're a dynamic cohort of engineers dedicated to leveraging innovations for Amazon's PXT Business Analytics tools and software. Together, we confront tangible challenges head-on, poised to revolutionize customer experiences in unforeseen ways. Every day, we embark on a journey of invention, pioneering fresh solutions that shape tomorrow's landscape.<br/><br/>As part of Amazon PeopleInsights eXperience (APIX) team  at Amazon, you will be part of the Data team that builds the foundational data infrastructure and analytics tools for people analytics capabilities. We create secure, scalable PXT LakeHouse solutions that enable teams across PXT to access and analyze data effectively while maintaining data integrity. In this role, you will design, build, and maintain scalable data pipelines and infrastructure, collaborate with product managers, business intelligence engineers, and HR business partners to transform complex HR Ops, experience and engagement  data into actionable insights that drive Amazon's people strategy. Your technical expertise will help us make data-driven decisions that enhance the employee experience across Amazon's global workforce.<br/><br/>Key job responsibilities<br/>Key job responsibilities<br/>In this role you will:<br/>* Design and implement high performant and cost-efficient data lake infrastructure using AWS big data stack, Spark, Hive, SQL, Apache Airflow, AWS Glue, EMR, S3, Redshift and OLAP technologies.<br/>* Collaborate with Business Intelligence Engineers to recognize and help adopt best practices in building semantic layers  in reporting and analysis, optimize SQL queries for fast, cost-efficient access.<br/>* Follow software best practices including coding standards, code reviews, and testing for all related data processing systems.<br/>* Work directly with customers to integrate new data types, curate data profiles,  perform data quality checks and incorporate feedback.<br/>* Empower technical and non-technical, internal customers to drive their own analytics and reporting (self-serve reporting) and support ad-hoc data generation and reporting when needed.<br/>* Be comfortable with a degree of ambiguity and willing to develop quick proof of concepts, iterate and improve<br/>* Actively support and foster a culture of inclusion.<br/><br/>A day in the life<br/>Successful candidate should have experience working with big data, building data lakes and data processing services, experience with one or more query language (e.g., SQL, PL/SQL, HiveQL, SparkSQL) and scripting language (e.g., Python, Scala). They are effective at seeing data patterns and building generic data solutions to improve user experience.<br/><br/>About the team<br/>The Amazon People Insights team transforms the creation and delivery of actionable, people-centric insights for HR, Operations, and corporate leaders across Amazon - empowering efficient, data-driven, and timely workforce decisions aligned with Amazon\u2019s objective to be Earth\u2019s Best Employer. ",
    "department_cost_center": null,
    "description_short": "Are you driven by the excitement of unraveling intricate data puzzles? Does your DNA resonate with collaborative problem-solving? Do you thrive on witnessing the ripple effects of your contributions in",
    "display_distance": null,
    "id": "786c9d5c-1bec-4f7a-8a34-b67a442f928f",
    "id_icims": "3182677",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/3182677/data-engineer-amazon-peopleinsights-experience-apix",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA54\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [
      "amazonian-experience-and-tech.team-aet",
      "pxt.team-amazonian-experience-and-technology"
    ],
    "posted_date": "February 17, 2026",
    "preferred_qualifications": "- Experience with AWS technologies like Redshift, S3, AWS Glue, EMR, Kinesis, FireHose, Lambda, and IAM roles and permissions<br/>- Experience with non-relational databases / data stores (object storage, document or key-value stores, graph databases, column-family databases)<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Seattle - 132,100.00 - 178,800.00 USD annually",
    "primary_search_label": "amazonian-experience-and-tech.team-es-technology",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, Amazon PeopleInsights eXperience (APIX)",
    "university_job": null,
    "updated_time": "about 4 hours",
    "url_next_step": "https://account.amazon.com/jobs/3182677/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-es-technology",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Experience with one or more query language (e.g., SQL, PL/SQL, DDL, MDX, HiveQL, SparkSQL, Scala)<br/>- Experience with one or more scripting language (e.g., Python, KornShell)",
    "business_category": "amazonian-experience-and-tech",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Are you driven by the excitement of unraveling intricate data puzzles? Does your DNA resonate with collaborative problem-solving? Do you thrive on witnessing the ripple effects of your contributions in the larger scheme of things? If you've nodded along to any of these questions, welcome to Amazon PeopleInsights eXperience (APIX) team! We're not just a team; we're a dynamic cohort of engineers dedicated to leveraging innovations for Amazon's PXT Business Analytics tools and software. Together, we confront tangible challenges head-on, poised to revolutionize customer experiences in unforeseen ways. Every day, we embark on a journey of invention, pioneering fresh solutions that shape tomorrow's landscape.<br/><br/>We are currently seeking a talented and motivated Data Engineer. In this role, you will be building data engineering applications using AWS stack. You should have deep expertise and passion in working with large data sets, data visualization, building complex data processes, performance tuning, bringing data from disparate data stores and programmatically identifying patterns. You should have excellent business acumen and communication skills to be able to work with business owners to develop and define key business questions and requirements. APIX has culture of data-driven decision-making, and demands timely, accurate, and actionable business insights.<br/><br/>Key job responsibilities<br/>In this role you will:<br/>- Design, implement, and support business critical data warehouse / data lake infrastructure using AWS big data stack, Python, Redshift, Glue/lake formation, EMR/Spark/Scala, Athena etc in a stable, low cost model.<br/>- Collaborate with Business Intelligence Engineers to recognize and help adopt best practices in reporting and analysis: data integrity, test design, analysis, validation, and documentation<br/>- Internalize our customer challenges and derive creative solutions which apply new and innovative technology.<br/>- Work directly with customers to integrate new data types, equipment, and incorporate feedback.<br/>- Empower technical and non-technical, internal customers to drive their own analytics and reporting (self-serve reporting) and support ad-hoc reporting when needed.<br/>- Help continually improve ongoing reporting and analysis processes, automating or simplifying self-service support for customers.<br/>- Be comfortable with a degree of ambiguity and willing to develop quick proof of concepts, iterate and improve<br/>- Apply software best practices including coding standards, code reviews, source control management, agile development, build processes, and testing.<br/>- Actively support and foster a culture of inclusion.<br/><br/>A day in the life<br/>Successful candidate should have experience working with big data, building data warehouses and data processing services. They are effective at seeing data patterns and building generic data solutions to improve user experience.<br/><br/>About the team<br/>Our mission is to harness the power of people data to empower PXT and people leaders to make decisions that help Amazon become the Earth\u2019s Best Employer.",
    "department_cost_center": null,
    "description_short": "Are you driven by the excitement of unraveling intricate data puzzles? Does your DNA resonate with collaborative problem-solving? Do you thrive on witnessing the ripple effects of your contributions in",
    "display_distance": null,
    "id": "63ba67c0-6ce8-4f7e-88b2-18fbcc9eaa78",
    "id_icims": "3182676",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/3182676/data-engineer-amazon-peopleinsights-experience-apix",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA54\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [
      "amazonian-experience-and-tech.team-aet",
      "pxt.team-amazonian-experience-and-technology",
      "operations.team-data-science",
      "operations.team-data-engineering"
    ],
    "posted_date": "February 17, 2026",
    "preferred_qualifications": "- Experience with big data technologies such as: Hadoop, Hive, Spark, EMR<br/>- Experience with any ETL tool like, Informatica, ODI, SSIS, BODI, Datastage, etc.<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Seattle - 101,300.00 - 160,000.00 USD annually",
    "primary_search_label": "amazonian-experience-and-tech.team-es-technology",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, Amazon PeopleInsights eXperience (APIX)",
    "university_job": null,
    "updated_time": "about 16 hours",
    "url_next_step": "https://account.amazon.com/jobs/3182676/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-es-technology",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "basic_qualifications": "- 1+ years of data engineering experience<br/>- 1+ years of analyzing and interpreting data with Redshift, Oracle, NoSQL etc. experience<br/>- Experience with data modeling, warehousing and building ETL pipelines<br/>- Knowledge of writing and optimizing SQL queries in a business environment with large-scale, complex datasets<br/>- Experience with one or more scripting language (e.g., Python, KornShell, Scala)",
    "business_category": "amazonian-experience-and-tech",
    "city": "Seattle",
    "company_name": "Amazon.com Services LLC",
    "country_code": "USA",
    "description": "Are you driven by the excitement of unraveling intricate data puzzles? Does your DNA resonate with collaborative problem-solving? Do you thrive on witnessing the ripple effects of your contributions in the larger scheme of things? If you've nodded along to any of these questions, welcome to Amazon PeopleInsights eXperience (APIX) team! We're not just a team; we're a dynamic cohort of engineers dedicated to leveraging innovations for Amazon's PXT Business Analytics tools and software. Together, we confront tangible challenges head-on, poised to revolutionize customer experiences in unforeseen ways. Every day, we embark on a journey of invention, pioneering fresh solutions that shape tomorrow's landscape.<br/><br/>We are currently seeking a talented and motivated Data Engineer. In this role, you will be building data engineering applications using AWS stack. You should have deep expertise and passion in working with large data sets, data visualization, building complex data processes, performance tuning, bringing data from disparate data stores and programmatically identifying patterns. You should have excellent business acumen and communication skills to be able to work with business owners to develop and define key business questions and requirements. APIX has culture of data-driven decision-making, and demands timely, accurate, and actionable business insights.<br/><br/><br/><br/>Key job responsibilities<br/>In this role you will:<br/>- Design, implement, and support business critical data warehouse / data lake infrastructure using AWS big data stack, Python, Redshift, Glue/lake formation, EMR/Spark/Scala, Athena etc in a stable, low cost model.<br/>- Collaborate with Business Intelligence Engineers to recognize and help adopt best practices in reporting and analysis: data integrity, test design, analysis, validation, and documentation<br/>- Internalize our customer challenges and derive creative solutions which apply new and innovative technology.<br/>- Work directly with customers to integrate new data types, equipment, and incorporate feedback.<br/>- Empower technical and non-technical, internal customers to drive their own analytics and reporting (self-serve reporting) and support ad-hoc reporting when needed.<br/>- Help continually improve ongoing reporting and analysis processes, automating or simplifying self-service support for customers.<br/>- Be comfortable with a degree of ambiguity and willing to develop quick proof of concepts, iterate and improve<br/>- Apply software best practices including coding standards, code reviews, source control management, agile development, build processes, and testing.<br/>- Actively support and foster a culture of inclusion.<br/><br/>A day in the life<br/>Successful candidate should have experience working with big data, building data warehouses and data processing services. They are effective at seeing data patterns and building generic data solutions to improve user experience.<br/><br/>About the team<br/>Our mission is to harness the power of people data to empower PXT and people leaders to make decisions that help Amazon become the Earth\u2019s Best Employer.",
    "department_cost_center": null,
    "description_short": "Are you driven by the excitement of unraveling intricate data puzzles? Does your DNA resonate with collaborative problem-solving? Do you thrive on witnessing the ripple effects of your contributions in",
    "display_distance": null,
    "id": "3d6373d7-9515-4c71-9d74-773a02596b50",
    "id_icims": "3182691",
    "is_intern": null,
    "is_manager": null,
    "job_category": "Data Science",
    "job_family": "Data Engineering",
    "job_function_id": null,
    "job_path": "/en/jobs/3182691/data-engineer-pxt-peopleinsight",
    "job_schedule_type": "full-time",
    "location": "US, WA, Seattle",
    "locations": [
      "{\"normalizedStateName\":\"Washington\",\"normalizedCountryCode\":\"USA\",\"city\":\"Seattle\",\"countryIso3a\":\"USA\",\"countryIso2a\":\"US\",\"locationNonStemming\":\"United States, WA, Seattle\",\"coordinates\":\"47.60357,-122.32945\",\"normalizedCountyName\":\"King\",\"type\":\"ONSITE\",\"normalizedCountryName\":\"United States\",\"normalizedLocation\":\"Seattle, Washington, USA\",\"location\":\"US, WA, Seattle\",\"region\":\"WA\",\"buildingCodeList\":[\"SEA54\"],\"normalizedCityName\":\"Seattle\"}"
    ],
    "normalized_location": "Seattle, Washington, USA",
    "optional_search_labels": [
      "amazonian-experience-and-tech.team-aet",
      "pxt.team-amazonian-experience-and-technology"
    ],
    "posted_date": "February 17, 2026",
    "preferred_qualifications": "- Experience with any ETL tool like, Informatica, ODI, SSIS, BODI, Datastage, etc.<br/>- Experience with big data processing technology (e.g., Hadoop or ApacheSpark), data warehouse technical architecture, infrastructure components, ETL, and reporting/analytic tools and environments<br/><br/>Amazon is an equal opportunity employer and does not discriminate on the basis of protected veteran status, disability, or other legally protected status.<br/><br/>Our inclusive culture empowers Amazonians to deliver the best results for our customers. If you have a disability and need a workplace accommodation or adjustment during the application and hiring process, including support for the interview or onboarding process, please visit <a href=\"https://amazon.jobs/content/en/how-we-hire/accommodations\">https://amazon.jobs/content/en/how-we-hire/accommodations</a> for more information. If the country/region you\u2019re applying in isn\u2019t listed, please contact your Recruiting Partner.<br/><br/><p><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">The base salary range for this position is listed below. Your Amazon package will include sign-on payments and restricted stock units (RSUs). Final compensation will be determined based on factors including experience, qualifications, and location. Amazon also offers comprehensive benefits including health insurance (medical, dental, vision, prescription, Basic Life &amp; AD&amp;D insurance and option for Supplemental life plans, EAP, Mental Health Support, Medical Advice Line, Flexible Spending Accounts, Adoption and Surrogacy Reimbursement coverage), 401(k) matching, paid time off, and parental leave. Learn more about our benefits at </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://amazon.jobs/en/benefits\"><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">https://amazon.jobs/en/benefits</span></a><span style=\"color: rgb(35, 47, 62)\" class=\"ProseMirror-FontColor\">.</span></p><br/><br/>USA, WA, Seattle - 101,300.00 - 160,000.00 USD annually",
    "primary_search_label": "amazonian-experience-and-tech.team-es-technology",
    "source_system": "JobCreator",
    "state": "WA",
    "title": "Data Engineer, PXT PeopleInsight",
    "university_job": null,
    "updated_time": "about 4 hours",
    "url_next_step": "https://account.amazon.com/jobs/3182691/apply",
    "team.id": null,
    "team.business_category_id": null,
    "team.identifier": null,
    "team.label": "team-es-technology",
    "team.created_at": null,
    "team.updated_at": null,
    "team.image_file_name": null,
    "team.image_content_type": null,
    "team.image_file_size": null,
    "team.image_updated_at": null,
    "team.thumbnail_file_name": null,
    "team.thumbnail_content_type": null,
    "team.thumbnail_file_size": null,
    "team.thumbnail_updated_at": null,
    "team.hide_jobs": null,
    "team.title": null,
    "team.headline": null,
    "team.description": null
  },
  {
    "id": "R0833523",
    "title": "Associate Data Engineer",
    "company": "CVS Health",
    "location": "CT - Hartford",
    "posted_date": "2026-02-18T07:02:12.169153",
    "url_next_step": "https://cvshealth.wd1.myworkdayjobs.com/en-US/CVS_Health_Careers/job/CT---Hartford/Associate-Data-Engineer_R0833523",
    "description_short": "Associate Data Engineer",
    "source": "CVS Health"
  }
];